### ISSUE TITLE
enhancement: clear out agents with a checkin_time older than X

### ISSUE THREAD

**Issue by odd-meta** [PowerShellEmpire/Empire#10]
I don't seem to be able to give this a label, but to be clear this is a feature request/enhancement.

It would be useful to me to have the ability to issue a command in the agents context to remove agents with a checkin_time older than X.

Ultimately I would like to be able to automatically assign my agent(s) some metadata in the agent list related to how long since they last checked in, something along the lines of a staleness scale. The next logical progression would be performing batch operations (killing them, running a module on them, etc) on collections of agents using their staleness as a selector.

**Comment by HarmJ0y** [comment]
So at this point, you can at least do "(Empire: agents) > list X" to display agents that have checked in in the last X minutes. We'll look into adding the ability to task/remove agents based on age, likely starting with a "remove agents past X minutes" type of thing.

**Comment by HarmJ0y** [comment]
Check out the StaleAgents branch now https://github.com/PowerShellEmpire/Empire/tree/StaleAgents

Added in "agents> remove X" to remove agents past X minutes of checkin, and "agents> list stale" and "agents> remove stale" to list/remove agents that have missed the maximum checkin interval. We'll merge the branch after some testing assuming there are no issues.

**Comment by enigma0x3** [comment]
This has been merged into master. Feel free to let us know if you have any additional requests or ideas!

Thanks!
