### ISSUE TITLE
screenshot memory leak

### ISSUE THREAD

**Issue by kokoown2** [PowerShellEmpire/Empire#100]
after you use the module screenshot the ps process becomes 400k memory usage.
after it sent, the process go down to 100k but not back to 60-30 as before.
memory leak?

**Comment by HarmJ0y** [comment]
If you run several dozen screenshots, does the memory continue to increase by ~40-70k each time?

**Comment by kokoown** [comment]
I will check it. I think its something to do with the send meassage funcrtion on agent.ps1

**Comment by kokoown** [comment]
I think that if you diwnload larg files you get the leak. Any solution?

**Comment by HarmJ0y** [comment]
Were you able to confirm if repeated screenshotting kept increasing memory utilization by ~40-70k each time? Trying to determine if this is a one-off increase due to some PowerShell weirdness or an actual issue that continues to bloat memory.

**Comment by kokoown** [comment]
No. Its a one time. I think it beacuse it send all the screenshot file in one time. That maybe to big to handle as png. Also during the file sending its incresing to 300mb process memory. And this ia very unlikley to send 1mb file. Maybe the answer is there?

**Comment by kokoown** [comment]
Is there a way to send the screenshoot file in parts?

**Comment by HarmJ0y** [comment]
Not at this point, no

**Comment by kokoown** [comment]
So maybe there ia a problem with the sending. Somehow its incresing rhe memory usage to very high levels. And its only 200k

**Comment by HarmJ0y** [comment]
Not sure about this- if it doesn't increase indefinitely it doesn't seem like a true memory leak.
