### ISSUE TITLE
Backgrounding Downloads

### ISSUE THREAD

**Issue by Ph1LZ** [PowerShellEmpire/Empire#109]
It would be nice to background file downloads.
'cause they are not right now.

**Comment by enigma0x3** [comment]
Good idea, we will definitely look at implementing this.

**Comment by HarmJ0y** [comment]
Unfortunately this isn't going to be easy due to the current agent architecture. We have someone working on a revamped jobs approach, after which it may be easier. If not we'll revisit and see if we can adapt the code in some way.

**Comment by enigma0x3** [comment]
Hey @Ph1LZ,
We currently have a development timeline set for some much needed updates to the internal architecture of the framework. We are laying the groundwork so we can work in the more "complex" architecture updates in the near future (background jobs being one of them). We definitely have this (with many other things) lined up to be added.

Thanks!
