### ISSUE TITLE
Ubuntu 14.04 x86_64: cannot get output from Agents (interact)

### ISSUE THREAD

**Issue by jaredbarez** [PowerShellEmpire/Empire#11]
Using latest commit (671635a5dad75fa295479d670b332977fc863ce4) and installed all required dependencies for Ubuntu 14.04 x86_64. Agents connect to listener, but the only command that actually outputs is "info". Tcpdump shows activity when issuing other interactive agent commands but output is never displayed.

**Comment by enigma0x3** [comment]
Hey jaredbarez,
After some additional testing, I am able to confirm that agent interaction works on Ubuntu 14.04.

<img width="917" alt="screen shot 2015-08-12 at 7 55 18 am" src="https://cloud.githubusercontent.com/assets/6264733/9223374/8d17b818-40c7-11e5-98e6-2b9c2801d3aa.png">

uname -a:
<img width="1031" alt="screen shot 2015-08-12 at 7 51 22 am" src="https://cloud.githubusercontent.com/assets/6264733/9223379/96ffb7fe-40c7-11e5-9646-4cefb5eeaf6a.png">

agent callback & command:
<img width="792" alt="screen shot 2015-08-12 at 7 53 24 am" src="https://cloud.githubusercontent.com/assets/6264733/9223382/a02766ec-40c7-11e5-98e7-603ed7cb9b28.png">

additional command:
<img width="686" alt="screen shot 2015-08-12 at 7 54 02 am" src="https://cloud.githubusercontent.com/assets/6264733/9223386/a888c524-40c7-11e5-981b-f75c256a8155.png">

Can you provide a little more information regarding your setup? What version of Windows are you running the stager on? It sounds like your agent is dying. Info is a server side command, meaning you can run it on dead agents. Can you verify that powershell.exe is running on the Windows system? You can also generate the stager and then remove the -NoP, -NonI and -W Hidden flags. When you run that on the system, the powershell window should be visible. Try that and make sure the agent is dying.

Can you take a screenshot of the wireshark capture and post it here as well?

Thanks!

**Comment by jaredbarez** [comment]
OK. I tried the following...
OS/Kernel version (it is in fact a Linux Mint but identifies as Ubuntu, as expected):
![p1](https://cloud.githubusercontent.com/assets/13761356/9230673/efe880a6-4123-11e5-9f47-66f9dce556e6.png)
IP of "Empire host" (yes I'm runnin it on my home WLAN):
![p2](https://cloud.githubusercontent.com/assets/13761356/9230700/2175381c-4124-11e5-94ea-1c772354720e.png)
iptables are "clean" (host is called "fud" :) and empire process is running on 8080/tcp:
![p3](https://cloud.githubusercontent.com/assets/13761356/9230756/6886020e-4124-11e5-8d69-0a69686b9555.png)
Connected agent from Windows 7 32-bit machine (it is VM running in bridge mode with uniq IP/MAC addr on this same Ubuntu host):
![p4](https://cloud.githubusercontent.com/assets/13761356/9230835/ec98010a-4124-11e5-9e6f-8cbe2c14961f.png)
Agent's powershell process as captured in Process Hacker (note that PID is now changed to 336 for I had to launch another agent - mistakenly kiled the first agent but everything behaves the same). This connection displays every 5 secs as set in agent's options:
![p5](https://cloud.githubusercontent.com/assets/13761356/9230918/86a7f750-4125-11e5-98ed-959921ec97ff.png)
Log of a correct beaconing from the agent (every 5 secs) as seen from Empire console:
![p6](https://cloud.githubusercontent.com/assets/13761356/9230957/c18d7462-4125-11e5-9430-a00a213c39ab.png)
And the beconing as seen from the Wireshark capture:
![p7](https://cloud.githubusercontent.com/assets/13761356/9230984/e1e488b8-4125-11e5-944b-639badb1e7d7.png)

I also tried to invoke some of bandwidth consuming commands blindly in order to see if command ever reaches the agent (i.e. download/upload commands creating local and remote files) but can confirm that no file is downoaded/uploaded nor the net traffic shows that. The dillema is does empire ever sends a command to the agent or the agents receives the command but for some reason doesn't execute it? In the packet capture I sent you every 200 OK response contained only default message, i.e. "It works!".
Of course I confirm that powershell process (i.e. the agent) does not die (as shown above)...

**Comment by enigma0x3** [comment]
Interesting. Let's do this. Can you do an apt-get update && apt-get upgrade on your Ubuntu box. Once that is done, rm -rf your empire folder and do a fresh clone from github. Once done, go into the setup folder (empire/setup) and run "install.sh". Make sure it installs all the required dependencies and then try it again.

Let me know your results. I was able to reproduce this if swig isn't installed, which is in the install script.

**Comment by jaredbarez** [comment]
Unfortunately, results are the same... except this time I noticed that immediatelly after launching empire throws some I/O errors:
![fail1](https://cloud.githubusercontent.com/assets/13761356/9235914/052a106a-4142-11e5-964c-0439a88d43f8.png)
I noticed these errors were also present all the time along. I just missed to see the output for empire cleans the screen upon launching. Any clues with this maybe ? I must admit I didn't peek into the code but if you know where exactly to look I'll be glad to help.

**Comment by enigma0x3** [comment]
Can you paste the contents of debug.log? It will be sitting in the empire directory

**Comment by jaredbarez** [comment]
Here it is but it seems correct (just agent connecting and my taskings attempts):

2015-08-12 21:12:51 Empire : [*] Empire starting up...
2015-08-12 22:28:32 EmpireServer : [*] Initializing HTTP server on 8080
2015-08-12 22:29:00 HttpHandler : [*] /index.asp requested from None at 192.168.5.15
2015-08-12 22:29:00 Agents : [*] Sending stager (stage 1) to 192.168.5.15
2015-08-12 22:29:01 HttpHandler : [*] Post to /index.jsp from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:01 Agents : [*] Agent MVPC4TGFZFMN1DHS from 192.168.5.15 posted to public key URI
2015-08-12 22:29:01 Agents : [*] Agent MVPC4TGFZFMN1DHS from 192.168.5.15 posted valid RSA key
2015-08-12 22:29:01 HttpHandler : [*] Post to /index.php from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:01 Agents : [*] Sending agent (stage 2) to MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:02 Agents : [+] Initial agent MVPC4TGFZFMN1DHS from 192.168.5.15 now active
2015-08-12 22:29:07 HttpHandler : [*] /news.asp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:10 Agents : [*] Tasked MVPC4TGFZFMN1DHS to run TASK_SHELL
2015-08-12 22:29:12 HttpHandler : [*] /admin/get.php requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:14 Agents : [*] Tasked MVPC4TGFZFMN1DHS to run TASK_SYSINFO
2015-08-12 22:29:17 HttpHandler : [*] /login/process.jsp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:22 HttpHandler : [*] /news.asp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:27 HttpHandler : [*] /news.asp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:31 Agents : [*] Tasked MVPC4TGFZFMN1DHS to run TASK_SHELL
2015-08-12 22:29:32 HttpHandler : [*] /login/process.jsp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:35 Agents : [*] Tasked MVPC4TGFZFMN1DHS to run TASK_SHELL
2015-08-12 22:29:38 HttpHandler : [*] /login/process.jsp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:43 HttpHandler : [*] /news.asp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:48 HttpHandler : [*] /news.asp requested from MVPC4TGFZFMN1DHS at 192.168.5.15
2015-08-12 22:29:53 HttpHandler : [*] /news.asp requested from MVPC4TGFZFMN1DHS at 192.168.5.15

**Comment by enigma0x3** [comment]
Interesting. Let me download and standup a brand new 14.04 ubuntu iso and try this completely fresh. We have only tested (and verified) Empire on Kali...so I recommend migrating to Kali (if you want to play with it while we work on getting this resolved).

Are you using Ubuntu desktop or Ubuntu server? Want to make sure I am using the same ISO as you.

**Comment by jaredbarez** [comment]
As I noted before it is in fact Linux Mint (17.2 "Rafaela"), which is based on desktop version of Ubuntu 14.04. It can be found at its usual place i.e. http://www.linuxmint.com/edition.php?id=190
As my primary "engagement" evironment is Kali I will try to launch it from there (i.e. Kali 2.0). Please don't waste your efforts if Kali and vanilla Ubuntu 14.04 are your primary platforms of interest. Just my 2c

**Comment by enigma0x3** [comment]
ahhh, I missed that. I'll get that downloaded tonight and test things.

**Comment by jaredbarez** [comment]
In that case please do post your findings after the testing. I'm now so curious about it. tnx

**Comment by jaredbarez** [comment]
I just tested this on Kali 2.0 and it fails the same way - i.e. no output from agents! 
My setup is host OS Linux Mint 17.2 64-bit which hosts two guests: VM1 is Kali 2.0 64-bit fully patched, VM2 is Windows 7 Pro 32-bit fully pathched. Both Kali VM and Windows VM run in bridged network mode. 
An interesting thing to see is now lack of I/O errors but instead of that empire in Kali shows some chars like a kind of terminal ESC codes in the same place as those I/O errors before:


![fail](https://cloud.githubusercontent.com/assets/13761356/9238591/e999cdec-4153-11e5-8c63-e803c25cdc99.png)

**Comment by enigma0x3** [comment]
That is odd. downloading Kali 2.0 now and will get it tested. 

Thanks for your patience!

**Comment by sixdub** [comment]
So we got the IOError worked out. The IOError was due to the interfaces as it tried to set up the default listener. It should not be removed and handled property. With that said, that should have had no impact on the specific error you are seeing. We have the tool up and running on Kali 2.0 and are working to recreate the issue. Banging our heads a little bit at this point... We will keep you updated. Thanks!

**Comment by jaredbarez** [comment]
OK. I just installed Kali 2.0 64-bit on a spare laptop (i.e. bare metal install) and will try to control the agents connecting from Windows 7 32-bit guest VM (which is running on Linux Mint 17.2 64-bit host OS, as you already know). The reason I didn't installed Win 7 on a bare metal is lack of the third laptop... (but can later reinstall that spare laptop with it...  my squaw will scalp-torture me :-).

**Comment by enigma0x3** [comment]
Hey man, any luck on getting this to work on Kali 2.0? We have decided to fully support 2.0 and have had multiple people test with success. 

Thanks!

**Comment by CicadaMikoto** [comment]
I am testing on the next-to-newest version of Kali x64 and I am also not receiving any output from my agents.  The individual agent logs show that the agents are queued to execute the commands, but nothing ever happens on the target box and no data is sent back to empire.  I also tried using the trollsploit modules to generate on-screen messages, but without success.  I am unsure how to proceed, as I have rm -rf'd Empire and git cloned three times now.  I am up-to-date on dependencies, so I'm confused.

**Comment by enigma0x3** [comment]
This shouldn't matter, but I'm running out of ideas as we have had no other reports of this issue. Is windows firewall on and do you have AV installed that implements its own firewall? What is your environment like?

**Comment by jaredbarez** [comment]
Sorry, I am offline next few days due to nontechnical issues... Will test and report as soon as get back. Stay tuned. Tnx

**Comment by Jehovah28** [comment]
Same problem on my machines. I have tried this on three different Kali Versions (1.0.8, 1.1.0  and 2.0) and I am not receiving any output from the agents, too. All machines are VMs on a Hyper-V Server. I've tried to disable the Firewall on the target to see if this is causing the Problem but no success. I've also used three different Windows Versions (Win 7 Enterpise, Win 8.1 Enterpise and Win 10 Enterprise) as Targets but the result is always the same.

**Comment by enigma0x3** [comment]
What commands are you issuing to the agents?

**Comment by enigma0x3** [comment]
Also, can you post a screenshot of your listener config as well as your agent info? Then post the ping results between your kali box and the windows target. Also, if you can, throw up a screenshot of the commands you are trying to run on the agents.

**Comment by Jehovah28** [comment]
Listener config (everything Default except the Name)
![listener](https://cloud.githubusercontent.com/assets/12220970/9306479/e170ee0e-44f8-11e5-8e96-f737597259ff.jpg)

Initial Agent Setup and test with ipconfig:
![agent](https://cloud.githubusercontent.com/assets/12220970/9306105/864f2858-44f6-11e5-9f69-d926dcce4f00.jpg)

test with an module:
![module](https://cloud.githubusercontent.com/assets/12220970/9306214/20ee394e-44f7-11e5-921c-0b660a72a407.jpg)

Agent responding:
![responding agent](https://cloud.githubusercontent.com/assets/12220970/9306233/419b393a-44f7-11e5-9a5f-fcb8e697a6ff.jpg)

Ping results:
![ping result](https://cloud.githubusercontent.com/assets/12220970/9306304/b7c9705e-44f7-11e5-847f-99a25a95f28f.jpg)

It seems everything is fine but as you see their's no Output

Here is the Output from the Debugging log:
![log](https://cloud.githubusercontent.com/assets/12220970/9306396/587fb08a-44f8-11e5-85f0-efa052bf866f.jpg)

**Comment by sixdub** [comment]
Okay, thanks for all the info. We have had a couple instances of this. We have been working to try to track it down but unfortunately have been unable to recreate. We will check everything out and get back to you if we can track it down...

**Comment by enigma0x3** [comment]
Hey @Jehovah28, I do have one question. While testing, I noticed that sometimes the agents can take a little longer than expected to return output. By default, they checkin every 5 seconds. Just to be sure, can you execute the "ps" command then then just let it sit for a minute or two? I want to make sure that there just isn't a long delay before output is displayed vs no output at all.

Thanks!

**Comment by Jehovah28** [comment]
I have tried this and waited for round about 5 minutes but nothing happend.
I've also installed 3 new vms on another Hypervisor but the results are the same.

**Comment by jaredbarez** [comment]
Just pulled latest Empire and setup a test on two bare metal PC installs (i.e. no virtualization of any kind): PC1 == Kali 2.0 64-bit + Empire listener, PC2 == Windows 7 32-bit + agent. Unfortunately, the results are the same as before (i.e. agent successfully connect but no interactive command ever executes from Empire console). :-(

**Comment by enigma0x3** [comment]
Interesting. Going back to virtualization, what virtualization platform do you have? Is there anyway you can set your Kali VM and your Windows VM to "host only"? This will help rule out any networking related issues. Both boxes should be in their own internal network and able to reach eachother. If you can test that, it will give us a better idea if this is network related or not as we have people using Empire on 2.0 with no issue

**Comment by jaredbarez** [comment]
OK. I just did that with no success. Two VMs with OS config/versions are same as in my bare metal test above. Network is in host-only mode for both VMs. Ping works when initiated from both directions, agent connects to Empire and beacons every default 5 secs as usual. Still no output from interactive commands! GRRRRR! This is just plain crazy.

**Comment by enigma0x3** [comment]
This would be much easier if I could just buy you a few beers and troubleshoot with you :)
What stager are you using? I'm running out of things to check. Gonna ping @sixdub  and @HarmJ0y to see if they have any additional input.

**Comment by jaredbarez** [comment]
Man, it works now! 
![screenshot-area-2015-08-19-145350](https://cloud.githubusercontent.com/assets/13761356/9356782/806a122a-4683-11e5-82f6-f6c6dc802811.png)

![screenshot-area-2015-08-19-145414](https://cloud.githubusercontent.com/assets/13761356/9356798/92f7f092-4683-11e5-8c1e-f3b7ecfb8f26.png)

**Comment by enigma0x3** [comment]
....what? It randomly starts working?

**Comment by jaredbarez** [comment]
I changed all Windows locale settings to English/US and it worked like a charm. :-) Yes, I live outside of US (i.e. Europe).

**Comment by enigma0x3** [comment]
Wow, that is interesting. Glad you go it working! @CicadaMikoto and @Jehovah28, you might check that and see if it resolves it for you.

**Comment by sixdub** [comment]
This actually helps a lot! we will be setting up a non-english US system for testing. Thanks so much!

**Comment by jaredbarez** [comment]
Just to elaborate a bit, my Windows system in not translated in English/US i.e. all strings are still English/US but regional settings and locale was set to other country. I also use dual keyboard layout i.e. English/US + other one (and switch layouts when needed). Hope it helps a bit. Cheerz

**Comment by CicadaMikoto** [comment]
Hey guys,

That’s not my issue, but I will be playing with it some more to see if there are any quirks in my setup.

I’ll take you up on that beer, though.  If you’re anywhere near Charlotte, NC, send me a PM :)

**Comment by Jehovah28** [comment]
Changed local settings and it is now working :-)

**Comment by HarmJ0y** [comment]
We recently pushed some changes to master that hopefully deal with the locale/international issues, however we have limited applicable systems to properly test on. When you get a chance, update from master and see if the new code resolves the previous issues.

**Comment by CicadaMikoto** [comment]
Excellent!  Will do.

**Comment by necony286** [comment]
i have the same problem but this didnt fix it :S

**Comment by necony286** [comment]
all the regional settings and locale are set to  English US...

**Comment by necony286** [comment]
well this fixed it for me 
thx to
@HarmJ0y 
I'm guessing the likely issue is the epoch syncing- on one of the client negotiation steps, the server sends its current epoch time to the agent the agent uses to calculate the epoch diff between it and the C2 server. This is used with a 5 minute sliding window to validate packets on the agent side as well as the packets on the server side.

The purpose of this was to provide some anti-replay functionality. My guess is that the time components are getting botched somehow. If you comment out this code in agent.ps1 and replace this line in packets.py with "return True", that should side step the epoch validation.

**Comment by NemoEht** [comment]
I'm having this same issue. Was there ever a fix found? If I took screenshots it would be the exact same as @Jehovah28.

**Comment by artagel** [comment]
I had this same issue (not the language related one).  It ended up being time skew on my VMs.  
I think having the anti-replay is nifty, but if it is happening, maybe there should be a notice.
