### ISSUE TITLE
time changes influence on agent.ps1

### ISSUE THREAD

**Issue by kokoown2** [PowerShellEmpire/Empire#111]
i was tring to debug a connection problem between my server and agent and i found out that if i have set the clock to a wrong date the agent will not get tasks from the server

in debug i found this on agent.ps1

# if the epoch counter isn't within a +/- 10 minute range (600 seconds)
        #   skip processing this packet
        if ($counter -lt ($ServerEpoch-600) -or $counter -gt ($ServerEpoch+600)){
            return
        }

this condition dont pass the tasks if the time zones arent correct
why so?
can i remove this condition?
what does it spouse to do anyway?

**Comment by HarmJ0y** [comment]
sure, you can remove this condition- the original idea was to introduce some basic anti-replay logic that prevents third parties from replaying packets between both parties.

**Comment by enigma0x3** [comment]
Like @HarmJ0y said, you can always remove it if it is causing issues with agent comms.
