### ISSUE TITLE
Scale issues with great than 20 agents

### ISSUE THREAD

**Issue by Shellntel** [PowerShellEmpire/Empire#113]
Have a repeatable issue where I run credentials/mimikatz/logonpasswords on greater than 20 agents and the agents then become unresponsive.

**Comment by enigma0x3** [comment]
Is it just that single module or is it any module executed on more than 20 agents?

**Comment by Shellntel** [comment]
I have only noticed it running that single module.

**Comment by curi0usJack** [comment]
I've noticed it only with mimikatz. Says that the command fires, but nothing comes back and agents go unresponsive to all other commands.

**Comment by enigma0x3** [comment]
Interesting, I'm willing to bet it has something to do with the fact that the mimikatz dll is being loaded 20+ times when running it against that many agents at once. I will play with it and see what is up.

Thanks!

**Comment by enigma0x3** [comment]
Does anything come back up or does everything stay dead/unresponsive?

**Comment by Shellntel** [comment]
The agents are generally dead/unresponsive. I can still see traffic from them on the interface; however,  I am unable to perform any type of interaction with the agents. Also, there will be output from maybe the first agent running mimikatz, but none of the others.

**Comment by enigma0x3** [comment]
just to verify, are you setting the "Agent" option to "all" within the module when you experience this?

**Comment by Shellntel** [comment]
Yes that is correct.

**Comment by Shellntel** [comment]
I personally haven't been in the position to test it with 1.4 yet. Not sure if that makes any difference.

**Comment by enigma0x3** [comment]
Hey all, I plan on getting to this sometime this week..been a bit busy at work. I'll post back here if I am able to reproduce. Thanks for your patience!

**Comment by enigma0x3** [comment]
I just tested this and was able to confirm with 37 agents. Bouncing the server causes the agents to come back and become responsive. Due to this, the issue is with the control server and not the agent. We are going to look at the control server and see if there is a way to limit the impact that high volume has on the server. In the meantime, I recommend simply picking agents to run mimikatz on.

**Comment by enigma0x3** [comment]
Hey all,
As an update...I am having some different results when testing. I started 45 agents and ran mimikatz on all of them. The agents did stop responding but only while the dll was being pushed down to all the agents...once each agent had the dll, they came back and posted results. I had to wait roughly 20-30 minutes until they came back though. 

Just to verify, if you let the agents sit after invoking mimikatz on all of them, do they ever come back? (it might take a bit).

**Comment by enigma0x3** [comment]
Hey @Shellntel,
Just following up on this. After some testing, it appears that the reason for the delay in checkins after tasking all agents with running mimikatz is due to pushing the mimikatz dll down 20+ times (at the same time) and then handling output
