### ISSUE TITLE
launcher proxy option only work on the first 3 times http requests

### ISSUE THREAD

**Issue by L34Rn** [PowerShellEmpire/Empire#115]
I start a http proxy server by BurpSuite, and set the launcher proxy option.
But here's a surprise: the proxy option only worked on first 3 times http requests, then the agent connect server directly.
It's amazing.

**Comment by enigma0x3** [comment]
Currently, manual proxy settings are not passed to the agent and are only used during initial staging. Someone already opened an issue for this and we are working on adding it in: https://github.com/PowerShellEmpire/Empire/issues/53

**Comment by paleos** [comment]
only for info - this issue should be corrected (more info in #53 )
