### ISSUE TITLE
After lateral movement some modules doesnt work due the admin/system context

### ISSUE THREAD

**Issue by kokoown** [PowerShellEmpire/Empire#116]
After I spread in the network with Wmi or psexec, my new agents running with system/admin privileges and doing just fine. Thw problem become when I try to use modules that require to run in user context. 
For example - screenshoot, keylooger.
Other modules works just fine. 

I have tried to impersonate to the local user but this still not working, maybe beacuse it's run on a different thread. 
Thanks for all the support

**Comment by kokoown** [comment]
The problem appar to be when running these module from system user. If there a way to open new agent with user account and uac privileges it shold solve the problem

**Comment by enigma0x3** [comment]
Some modules require you to be running in the context of the domain user. If you only have a SYSTEM agent, you can either inject into a process running under the context of the target user or you can use "steal_token" to steal the token of that particular process. I recommend simply injecting into a process running as the user. This will give you an agent back in that users context.
