### ISSUE TITLE
Little help getting around

### ISSUE THREAD

**Issue by josecgcorreia** [PowerShellEmpire/Empire#123]
Hello all,

I have a quick question, is empire able to connect to agents outside the local network?

I looked at the Listeners foreign Type but cant really get it to work. My external ip is 194.65.40.21 (something like this) the only thing i should do was put the Listener Host to that ip, and the type to foreign, or am i doing all wrong? Once i generate a .bat file and run on another machine on another network it doesnt connect to my Listener.

Best Regards,
José

**Comment by enigma0x3** [comment]
Yes, Empire is able to communicate over the internet. The setup is no different to any other RAT in the sense that you either need to put the controller on a public server with a public IP or you need to use port forwarding. You don't need a foreign listener, just set it up the same with a public IP and make sure everything is routable. 

Is that what you mean? If you have the controller on 1 network and you run a payload on another, the 2 have to be routable in the sense the agent's traffic has to be able to get to the controller.

**Comment by HarmJ0y** [comment]
The 'foreign' listener type is used to pass sessions between multiple Empire servers ([bottom of the page here](http://www.powershellempire.com/?page_id=102)) and isn't required for normal execution. If you set an IP/hostname for the **Host** option, it doesn't matter is the IP is internally or publicly routable, as long as the agent can communicate with that host. If you're failing to get communication, try verifying the reachability of the host, any host based protections, proxy issues, etc.
