### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by droctapus1** [PowerShellEmpire/Empire#124]
I am just starting to install this and I am getting the message below. I have run the installer a couple times, Setup the DB and attempted to reset as well. Any help?

Traceback (most recent call last):
  File "./empire", line 6, in <module>
    from lib.common import empire
  File "/tools/Empire/Empire-master/lib/common/empire.py", line 15, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch

**Comment by enigma0x3** [comment]
Are you running this on Kali?

**Comment by droctapus1** [comment]
Yes that would be corect

**Comment by HarmJ0y** [comment]
Did you run [./setup/install.sh](https://github.com/PowerShellEmpire/Empire/blob/master/setup/install.sh) ? The reason I ask is that it look likes one of the Python dependencies ([pydispatcher](https://github.com/PowerShellEmpire/Empire/blob/master/setup/install.sh#L25)) didn't install correctly on your machine. Can you rerun that install.sh script if you haven't already and record any errors that result? If that still fails, try running "pip install pydispatcher" and see if there's an error with that as well.

**Comment by droctapus1** [comment]
Sorry all this was all due to my proxy. I bypassed it and now its working so sorry for this post
