### ISSUE TITLE
Languages that are not UTF-8

### ISSUE THREAD

**Issue by Da5hes** [PowerShellEmpire/Empire#125]
after some testing today, empire crashed when we tried to download a file with a hebrew filename, my guess is that empire download function  does not support anything but UTF-8, so empire will crash on anything else than that

**Comment by HarmJ0y** [comment]
The problem with non-UTF-8 language sets is a known issue https://github.com/PowerShellEmpire/Empire/issues/24 . It's on the queue to look into but we haven't had time yet.

**Comment by HarmJ0y** [comment]
Pull the dev branch and let me know if this is an accurate fix https://github.com/PowerShellEmpire/Empire/commit/3cf322e76a3f3377b6337565a030e4d99b5c190d

If you're able to test on an English system as well to confirm nothing breaks, that would be awesome as well

**Comment by Da5hes** [comment]
thanks for the fast replay
empire is not totally crashing like before, but it is still not working(i did the test on a US language machine with a hebrew filename on it)

Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/Desktop/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/root/Desktop/Empire/lib/common/agents.py", line 1120, in process_get
    taskPacket = packets.build_task_packet(taskName, taskData)
  File "/root/Desktop/Empire/lib/common/packets.py", line 106, in build_task_packet
    return taskID + counter + length + data.encode('utf-8').encode('utf-8',errors='ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)

**Comment by enigma0x3** [comment]
hey @Da5hes,
Is this still an issue? I just tried to download a Hebrew filename on an en-us system and it worked ok for me:

<img width="789" alt="screen shot 2016-03-08 at 7 45 47 am" src="https://cloud.githubusercontent.com/assets/6264733/13602010/eaf84e32-e501-11e5-86aa-30aef407a2d2.png">

**Comment by enigma0x3** [comment]
@Da5hes,
If this is still an issue, feel free to comment back. In the meantime, closing.
