### ISSUE TITLE
New-HoneyHash.ps1 Creating Authentication Attempts

### ISSUE THREAD

**Issue by andersonalex740** [PowerShellEmpire/Empire#127]
I'm using New-HoneyHash.ps1 to store honey hashes and am noticing that, on some hosts, Event 4776 is being generated.  Initially, I thought the honeyhash had caught something.  However, upon further inspection, it seems like the API CreateProcessWithLogonW is responsible for the authentication attempt.

Any idea why this would be happening on some hosts and not others?

Thanks!

**Comment by HarmJ0y** [comment]
Honestly I'm not sure, if we get time we'll try to test this method and examine the authentication events
