### ISSUE TITLE
minor: list stale returns "[!] No agents currently registered" if no agents are stale

### ISSUE THREAD

**Issue by odd-meta** [PowerShellEmpire/Empire#13]
"list stale" command issued when no stale agents are present

<img width="877" alt="screen shot 2015-08-12 at 9 10 32 am" src="https://cloud.githubusercontent.com/assets/1418040/9227791/8ee4c2e8-40d2-11e5-9753-3c7f5422dacf.png">

after rebooting the agent box and waiting a minute

<img width="863" alt="screen shot 2015-08-12 at 9 10 40 am" src="https://cloud.githubusercontent.com/assets/1418040/9227808/a7cec57e-40d2-11e5-9fbe-993372937e68.png">

I could easily say that's a semantic issue, but my first reaction was, oh noe my agents are gone. A message along the lines of, "No currently stale agents", or something along those lines might be a little more appropriate.

**Comment by enigma0x3** [comment]
This is fixed now.

Thanks!
