### ISSUE TITLE
Chrome Dump memory consumption

### ISSUE THREAD

**Issue by topazbor** [PowerShellEmpire/Empire#130]
When using models with large file in it  (like Chrome Dump (System.Data.SQLite.dll))
the empire agent process is loading memory to 600k-500k for the task to be completed.
after it's finish the process normalize to ordinary memory usage - around 35k ~
this thing is very not normal and can cause anomaly detection to find my Agent while it is overloading.
This issue appear to be in more modules that send large file in it.
like PsInject and Mimikatz

**Comment by enigma0x3** [comment]
This is because the module is using the embedded dll. Once the dll is put into memory, the memory usage should normalize. This is a tradeoff when using capabilities that contain dlls that need to be loaded and is expected.
