### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by topazbor** [PowerShellEmpire/Empire#131]
I'm Re Issuing an old issue.
After running heavy modules my agent process doesn't collect the garbage right and the memory usage stay really high, and not cleaning - that is very suspicious
look on this picture
![chromedump - copy](https://cloud.githubusercontent.com/assets/17022179/13041600/6f3d423a-d3c1-11e5-8a12-40aa1d6dae96.png)

you can see video here:
https://youtu.be/kT68102Pg1o

It happans in modules like ChromeDump / PSinject / Mimikatz
I have tried to use [gc]::collect() manually but it still staying at 200k memory usage of the private working set.

I tried to debug the agent with get-variables but it's seems clean.

Is it possible to fix that problem?

**Comment by HarmJ0y** [comment]
We can't control the underlying memory usage for PowerShell beyond manually triggering the garbage collection.

**Comment by topazbor** [comment]
why?
so its doomed?

**Comment by HarmJ0y** [comment]
'Why' is that we're at the mercy of the exposed methods for the underlying components of the language. If this is a show-stopper for you, then you may want to investigate another solution.
