### ISSUE TITLE
NAT to NAT redirection

### ISSUE THREAD

**Issue by admiral123** [PowerShellEmpire/Empire#133]
Am looking to see if redirection from one NAT env to another is possible.  Have played with the RedirectTarget within Listeners and have also tried Pivot and Hop listeners to no avail.  What is the easiest way within Empire to execute a stager within one NAT'd environment to call back to another?

**Comment by HarmJ0y** [comment]
Try setting the listener type to 'Foreign' and manually building a listener with the config of the new IP. Let us know if that works.

**Comment by admiral123** [comment]
Thanks for the quick feedback.  That did not seem to work, but perhaps I am missing something.  Setup is as follows:
NAT'd empire box with listener -> Empire Firewall -> INTERNET -> Target Firewall -> NAT'd target

NAT'd empire = 1.1.1.1, Empire FW = 69.69.69.69
I setup the empire Listener to call back to 1.1.1.1 and set Foreign IP to 69.69.69.69?
Understand I have to do port forwarding on the Empire FW, and I am good with that, but this doesn't seem at all correct based on the documentation for Foreign.  Goal for me is to call back to the Empire FW and then allow port forwarding to the Empire box.  I can set the callback to the FW and forward to empire, but empire won't accept as it is not the correct IP.  Again, am obviously missing something.  Any/all assistance is greatly appreciated.

**Comment by enigma0x3** [comment]
Just so I understand correctly, are you setting your Empire listener to the public IP of the network you control and are forwarding the proper ports on the boundary to your Empire box? You should be able to just use a normal listener and set the IP to the public. Then from the router/firewall, you should be able to forward the port that Empire is listening on to the internal IP of your empire box.

**Comment by enigma0x3** [comment]
If this is still an issue, feel free to comment back. In the meantime, closing.
