### ISSUE TITLE
Invoke-ZipFolder

### ISSUE THREAD

**Issue by topazbor** [PowerShellEmpire/Empire#135]
Using this attack showing a progress bar
![image](https://cloud.githubusercontent.com/assets/17022179/13103676/ad4bf8a0-d560-11e5-8e55-07506521a08d.png)

**Comment by HarmJ0y** [comment]
Right now there's not a way around this. The 'System.IO.Compression.FileSystem' .NET method won't work on v 2.0, and the specified options to [hide the dialog](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787866(v=vs.85).aspx) don't work correctly. We'll look into it but it might be a restriction of v 2.0 compatibility that we'll have to live with.

**Comment by topazbor** [comment]
I have managed to do something like this, but I'm still getting errors

function gzip{
    param([string]$path)
    if (!(Test-Path $path)){ 
        return
    }
    $zipArchive = Resolve-Path $path | Select-Object Path -ExpandProperty Path
    $zipArchive +='.zip'
    [System.Reflection.Assembly]::Load("WindowsBase,Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35") | Out-Null
    $ZipPackage=[System.IO.Packaging.ZipPackage]::Open($zipArchive, [System.IO.FileMode]"OpenOrCreate", [System.IO.FileAccess]"ReadWrite")

    function zip {
        param([string]$path)
        $files = gci $path | Select-Object FullName -ExpandProperty FullName
        ForEach ($file In $files) {
           if (!(Test-Path $file -PathType Container)){ 
               try {
                    $bytes=[System.IO.File]::ReadAllBytes($file)
                    $file = ($file-replace "C:","" -replace "\\","/")
                    $file = $file -replace " ","$"
                    $partName=$null
                    $partName=New-Object System.Uri($file, [System.UriKind]"Relative")  
                    $part=$ZipPackage.CreatePart($partName, "application/zip", [System.IO.Packaging.CompressionOption]"Maximum")
                    $stream=$part.GetStream()
                    $stream.Write($bytes, 0, $bytes.Length)
                    $stream.Close()
               } catch {}
            }
            else{zip $file}
        }

    }
    zip $path
    $ZipPackage.Close()
    echp "Folder $path zipped to $path.zip"
}
gzip file
