### ISSUE TITLE
How to retrieve negotiation password?

### ISSUE THREAD

**Issue by ivalogic** [PowerShellEmpire/Empire#138]
How to retrieve negotiation password?
And is it editable?

**Comment by HarmJ0y** [comment]
Do:

`# sqlitebrowser ./data/empire.db`

Then browse to 'config' for the negotiation password or 'agents' for each agent's session key. ./setup/setup_database.py can set the staging key on db setup as well.

**Comment by ivalogic** [comment]
Thanks alot.
