### ISSUE TITLE
Stagers that start when Empire is not open

### ISSUE THREAD

**Issue by ivalogic** [PowerShellEmpire/Empire#140]
Are stagers that start when Empire is not open not meant to show up as agents?
Is this normal behavior?
If so what is the explanation?

**Comment by HarmJ0y** [comment]
If there's no controller up to handle agent communication, then the agent will not be staged and will not show up in the controller interface.

**Comment by ivalogic** [comment]
Although, if persistence measures have been taken, the agent should remain right?

**Comment by HarmJ0y** [comment]
The current persistence mechanisms don't store the complete staged agent- the phase 1 staging code is stored, which needs a control server to stage the logic from when it triggers.
