### ISSUE TITLE
my Empire agent dose not connect back to me

### ISSUE THREAD

**Issue by necony286** [PowerShellEmpire/Empire#142]
i start Empire
$ ./empire
$listeners
i had setup up a listener that worked yesterday (set Name,set Host, set Port, and everything else was left on default)
the listener is active and it had worked before i just opend it and i cant get the conncetion
i used the stager launcher
and copy paste it to cmd on target machine (this worked yesterday and today it dose not )

**Comment by enigma0x3** [comment]
In order for us to help you, you need to post details..

**Comment by enigma0x3** [comment]
try running ./reset.sh in the setup folder, generate a stager and run it on a box to see if it connects.

**Comment by enigma0x3** [comment]
Verify that you can ping your empire server.

**Comment by necony286** [comment]
ok i've done that and i  got a error msg:
[!] Error starting listener on port 20000: [Errno 98] Address already in use
so i i've opened terminal and typed  netstat -plten:
output:
ctive Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:9391          0.0.0.0:*               LISTEN      0          16822       797/openvassd: Wait
tcp        0      0 127.0.0.1:9392          0.0.0.0:*               LISTEN      0          16306       693/gsad        
tcp        0      0 0.0.0.0:20000           0.0.0.0:*               LISTEN      0          26872       1822/python

**Comment by enigma0x3** [comment]
I recommend rebooting the box that the empire server is running on, run the reset.sh script and regenerate your listeners and stagers.

**Comment by necony286** [comment]
ok ill try that. back to you in 3min

**Comment by necony286** [comment]
nope i don't get an agent. what should i do next ?

**Comment by necony286** [comment]
how do i ping my server?

**Comment by HarmJ0y** [comment]
Please read the documentation at http://www.powershellempire.com/?page_id=110

**Comment by necony286** [comment]
i've read that and im seem to be blind or just missing it. where exactly is the part about pinging ur empire server?

**Comment by necony286** [comment]
ok i found out how to ping (im such a noob, heh) 
but before that i'm gonna try rm -rf the empire folder and do a fresh install

**Comment by necony286** [comment]
:~/Empire/setup# ./setup_database.py

 [>] Enter server negotiation password, enter for random generation: necony286
Traceback (most recent call last):
  File "./setup_database.py", line 108, in <module>
    )''')
sqlite3.OperationalError: table config already exists

**Comment by necony286** [comment]
why did u close it i dont understand .... well that sad for me
