### ISSUE TITLE
How do I run Empire exe?

### ISSUE THREAD

**Issue by mattifestation** [PowerShellEmpire/Empire#143]
When I run powershell.exe, why doesn't it run Empire?

**Comment by mubix** [comment]
@mattifestation it does, could you stop please, i have enough agents ;-)

**Comment by mattifestation** [comment]
Can you please help? You should know what my issue is without me providing any context or reproduction steps. You guys are the devs. Come on, man.

**Comment by leechristensen** [comment]
https://github.com/blog/2111-issue-and-pull-request-templates :)

**Comment by mattifestation** [comment]
NM. I'll just use Metasploit...

**Comment by HarmJ0y** [comment]
"Remove-Item C:\* -Recurse -Force" should fix your issue.

**Comment by jamesshew** [comment]
$url='http://lmgtfy.com/?q=why+doesn%27t+it+run+empire&l=1'
Start-Process -FilePath "c:\Program Files\Internet Explorer\iexplore.exe" -ArgumentList $url

**Comment by trustedsec** [comment]
I have the same issue. When I run PowerShell I am not getting an Empire shell. Looking for help. Running BackTrack version 1 with python 1.2.

**Comment by BrandonEckert** [comment]
Does this work on windows 98 SE?

**Comment by synopsis19** [comment]
For those who may still be having this problem: try running the Windows Network Troubleshooter.  If you get a "can't identify the problem" result, that almost certainly means systemd has become corrupted on your machine. Set up dual-booting on the box with Windows 10 and the latest version of Solaris; most of the time that should resolve the issue.

**Comment by byt3bl33d3r** [comment]
I seem to be having the same issue running powershell scripts:
```
#~ chmod +x PowerView.ps1
#~ ./PowerView.ps1
```
Why it no worky?

**Comment by BrandonEckert** [comment]
Perhaps use the sudo? Sudo makes everything worky. Sh...py...ps1...bmp.

**Comment by mr64bit** [comment]
@byt3bl33d3r try adding
#!c:\Windows\System32\WindowsPowerShell\v1.0\powershell to the top of the
script.
