### ISSUE TITLE
my Empire agent dose not connect back to listener

### ISSUE THREAD

**Issue by necony286** [PowerShellEmpire/Empire#144]
u closed the issue i made but it didn't help me and i really want this to work so ( and im sorry if i did something that was wrong  or was wasting your time please spare few minutes u don't know how much this means to me)
i will try my best now !!!
I'm using kali 2.0 64 as my main OS, my target machine is windows 7 32 on VirtualBox running in my kali
1. i removed empire folder ( by typing rm -rf )
2. i did a fresh git clone from github
3.  ./setup/install.sh
4. ./setup/setup_database.py 
got this error her:
":~/Empire/setup# ./setup_database.py
 [>] Enter server negotiation password, enter for random generation: necony286b
Traceback (most recent call last):
  File "./setup_database.py", line 108, in <module>
    )''')
sqlite3.OperationalError: table config already exists"
so this was probably because i had it already installed.
5. i set up a listener (Name,Host,Port (im using dns and my port is opend  i checked at canyouseeme, and my noip is running))
6.i've pinged it heres the info:
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=54 ttl=63 time=1.82 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=55 ttl=63 time=1.87 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=56 ttl=63 time=1.94 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=57 ttl=63 time=2.05 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=58 ttl=63 time=2.09 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=59 ttl=63 time=1.93 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=60 ttl=63 time=1.92 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=61 ttl=63 time=4.59 ms
64 bytes from cable-89-216-203-122.dynamic.sbb.rs (89.216.203.122): icmp_seq=62 ttl=63 time=1.98 ms
--- neconianz.ddns.net ping statistics ---
62 packets transmitted, 62 received, 0% packet loss, time 61096ms

and from windows:
Pinging neconianz.ddns.net [89.216.203.122] with 32 bytes of data:
Reply from 89.216.203.122: bytes=32 time<1ms TTL=127
Reply from 89.216.203.122: bytes=32 time=2ms TTL=127
Reply from 89.216.203.122: bytes=32 time=2ms TTL=127
Reply from 89.216.203.122: bytes=32 time=5ms TTL=127

Ping statistics for 89.216.203.122:
Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
Minimum = 0ms, Maximum = 5ms, Average = 2ms

**Comment by necony286** [comment]
Listener Options:

  Name              Required    Value                            Description
  ----              --------    -------                          -----------
  KillDate          False                                        Date for the listener to exit (MM/dd/yyyy).
  Name              True        target                           Listener name.
  DefaultLostLimit  True        60                               Number of missed checkins before exiting
  StagingKey        True        a136d41e5fc3fe40da9b1e34849219a7 Staging key for initial agent negotiation.
  Type              True        native                           Listener type (native, pivot, hop).
  ID                True        1                                Listener ID.
  RedirectTarget    False                                        Listener target to redirect to for pivot/hop.
  DefaultDelay      True        5                                Agent delay/reach back interval (in seconds).
  WorkingHours      False                                        Hours for the agent to operate (09:00-17:00).
  Host              True        http://neconianz.ddns.net        Hostname/IP for staging.
  CertPath          False                                        Certificate path for https listeners.
  DefaultJitter     True        0.0                              Jitter in agent reachback interval (0.0-1.0).
  DefaultProfile    True        /admin/get.php,/news.asp,/login/ Default communication profile for the agent.
                                process.jsp|Mozilla/5.0 (Windows
                                NT 6.1; WOW64; Trident/7.0;
                                rv:11.0) like Gecko
  Port              True        20000                            Port for the listener.

**Comment by HarmJ0y** [comment]
![](http://i.imgur.com/VXSxAAE.gif)

**Comment by HarmJ0y** [comment]
![](http://i.imgur.com/aSpi3BF.jpg)

**Comment by necony286** [comment]
wow well thats not nice. can u let me know what did i do wrong?

**Comment by enigma0x3** [comment]
I recommend not using NoIP and keeping it all local to your machine.
