### ISSUE TITLE
Stage0 Continuous Attempts

### ISSUE THREAD

**Issue by jbertman** [PowerShellEmpire/Empire#146]
One of the issues I've had is stage0 agents missing their initial check-in for reasons unrelated to Empire. It would be great to be able to set a retry with a timeout on a stage0 payload. The attempts can be wrapped in a check on the `elapsed` property of a `[diagnostics.stopwatch]::StartNew()` instance inside a while loop. The timeout and delay can be configurable via `elapsed` and `start-sleep`.

**Comment by mubix** [comment]
Maybe make this an option in the stager generators?

**Comment by jbertman** [comment]
That's where I thought the best place for them would be as well.

**Comment by HarmJ0y** [comment]
Cool, we'll work on getting these implemented in the stager modules.

**Comment by HarmJ0y** [comment]
See if this works https://github.com/PowerShellEmpire/Empire/commit/08ca63fe0994a1b67b5987b7d28a8ea003c35ce1

If StagerRetries is set, the the default delay will be pulled from the listener config for the delay between retries.

**Comment by enigma0x3** [comment]
Hey @jbertman,
Let us know if the changes in the dev branch work for you.

Thanks!

**Comment by jbertman** [comment]
Checking it out now, thanks for the quick turnaround!

**Comment by jbertman** [comment]
Working great for me. Tested by swapping virtual NICs at random times that should fall into the retry window. Ready for closure unless anyone has any additions.

**Comment by enigma0x3** [comment]
We will run through some final tests and if all checks out, we will move it into master.

Thanks!

**Comment by HarmJ0y** [comment]
As the mod seems to work, will close this issue and merge to master soon as @enigma0x3 mentioned.
