### ISSUE TITLE
Running Empire under Mac OS X

### ISSUE THREAD

**Issue by macubergeek** [PowerShellEmpire/Empire#15]
Trying to install Empire under MacOSX v10.10.4
read the install.sh script to see what the dependencies are
installed what was missing.
when I launch empire I get:
MANDIANT> ../empire
Traceback (most recent call last):
  File "../empire", line 6, in <module>
    from lib.common import empire
  File "/Applications/GITLIST-PACKAGES/Empire/lib/common/empire.py", line 22, in <module>
    import http
  File "/Applications/GITLIST-PACKAGES/Empire/lib/common/http.py", line 18, in <module>
    import encryption
  File "/Applications/GITLIST-PACKAGES/Empire/lib/common/encryption.py", line 12, in <module>
    import base64, hashlib, hmac, string, M2Crypto
  File "build/bdist.macosx-10.10-intel/egg/M2Crypto/__init__.py", line 24, in <module>
  File "build/bdist.macosx-10.10-intel/egg/M2Crypto/ASN1.py", line 12, in <module>
  File "build/bdist.macosx-10.10-intel/egg/M2Crypto/BIO.py", line 221, in <module>
  File "build/bdist.macosx-10.10-intel/egg/M2Crypto/BIO.py", line 227, in CipherStream
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'

was hoping you could smack me in the head and tell me what stupid thing I've done (other than trying to run it under MacOSX of course ;-)

**Comment by enigma0x3** [comment]
We have only tested Empire under Ubuntu 14.04 LTS and Kali Linux. We will get OSX tested shortly

**Comment by davehardy20** [comment]
Hi,

Just for the record I have Empire running on Arch Linux :)

Dave

On 14 August 2015 at 13:53, enigma0x3 <notifications@github.com> wrote:

> We have only tested Empire under Ubuntu 14.04 LTS and Kali Linux. We will
> get OSX tested shortly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerShellEmpire/Empire/issues/15#issuecomment-131096677>
> .
>



-- 
Best Regards
David Hardy

Follow Me on Twitter @davehardy20 <http://twitter.com/davehardy20> LinkedIn
Profile <http://uk.linkedin.com/pub/david-hardy/6/388/2a2> pentest-N00b Blog
<http://pentestn00b.wordpress.com/>

**Comment by enigma0x3** [comment]
Awesome! no issues?

**Comment by davehardy20** [comment]
Nope, just added the dependencies and it ran first time, only issue I've
had is the one with the DLL payload and Metasploit, but that's not an
empire issue.

Dave

On 14 August 2015 at 14:03, enigma0x3 <notifications@github.com> wrote:

> Awesome! no issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerShellEmpire/Empire/issues/15#issuecomment-131098925>
> .
>



-- 
Best Regards
David Hardy

Follow Me on Twitter @davehardy20 <http://twitter.com/davehardy20> LinkedIn
Profile <http://uk.linkedin.com/pub/david-hardy/6/388/2a2> pentest-N00b Blog
<http://pentestn00b.wordpress.com/>

**Comment by enigma0x3** [comment]
Thanks @davehardy20!


@macubergeek,
We have decided that for the time being, version 1.0 will only support Kali Linux. This is due to development and testing time. Once Empire becomes aged and stable, we will revisit multi-platform support.

**Comment by byt3bl33d3r** [comment]
@enigma0x3 @macubergeek hey guys, just FYI the reason for that error is that the m2crypto bindings break when using swig > 3.0.4, the only solution at the moment seems to be downgrading, I'm running into this error myself running Arch linux

**Comment by byt3bl33d3r** [comment]
see https://github.com/swig/swig/issues/344 as reference

**Comment by byt3bl33d3r** [comment]
after more digging it seems that a pull request was submitted to fix this but it hasn't been merged yet https://github.com/martinpaljak/M2Crypto/pull/75

**Comment by paralax** [comment]
FWIW i got Empire launching (not fully tested) on OSX 10.10 with swig 3.0.4 (you can download from their archives page) and `pip install M2Crypto==0.21.1` - both older versions that work around this bug.

**Comment by HarmJ0y** [comment]
Good to hear!
