### ISSUE TITLE
bypassuac getting detected by av

### ISSUE THREAD

**Issue by necony286** [PowerShellEmpire/Empire#151]
how can i try to avoid this? are there any solutions to this problem ?
(the Avira picks it up and tries  to send it to the avira cloud (i never let it) but it wont run.  (and avira will figure out its a malware as soon as it run it thru the cloud)
cryptbase.ddl (somehow gets detected)

**Comment by enigma0x3** [comment]
I will test this. In the meantime, if you are on Windows 7, you can try the bypassuac_wscript module.

**Comment by HarmJ0y** [comment]
It's difficult to get into a cat and mouse game with AV, as it consumes too much time trying to evade every product out there. You're always free to roll a replacement dll that can be hijacked by sysprep.

**Comment by necony286** [comment]
is it possible to crypt ur dll ?  because  i lack the knowledge to my own dll

**Comment by HarmJ0y** [comment]
No, we will not be encrypting the dll, as we don't want to spend time getting into a race against specific AV engines.

**Comment by necony286** [comment]
so if i wanted to crypt the dll it would run normally with the rest of the empire?

**Comment by HarmJ0y** [comment]
sure have at it

**Comment by necony286** [comment]
ty, for ur time!
