### ISSUE TITLE
AV detects the Empire Macro as a Virus

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#152]
I used stager/macro to generate a macro for my listener, I added it to an Excel file, all works. Only issue, AV detects it as a virus.
The same AV does not detect a macro produced via Veil and macro_safe.py.

Any ideas on how to bypass AntiVirus detection for this?

**Comment by enigma0x3** [comment]
It is difficult to get involved in the "cat and mouse" game that offensive toolsets and defensive products often get involved in as it consumes a lot of time. We encourage people to modify things as needed to get around restrictions such as AV. I recommend checking out different methods of scrambling macro code. Most AV products are based on static signatures so it should be trivial to modify things enough to bypass it.

**Comment by honeyfairy** [comment]
Thank you for the reply, much appreciated.
For those who may be facing the same issue, from a beginner level point: 
I have so far tried CrunchCode for Excel, but received many errors and it did not scramble the macro code successfully.
