### ISSUE TITLE
Simplify the installation

### ISSUE THREAD

**Issue by forkmind** [PowerShellEmpire/Empire#153]
When you execute the installation script there are a few dependencies to install before getting empire running (I remember it was pycripto, etc...) and the setup does not works out of the box. Is there a way to install automaticly these dependencies when running the script ?

**Comment by HarmJ0y** [comment]
Running the [./setup/install.sh](https://github.com/PowerShellEmpire/Empire/blob/master/setup/install.sh) script should install all relevant dependencies. A statement like "the setup does not works out of the box" doesn't give us enough contextual information to determine what the potential issue you're encountering may be.

Also, what do you mean exactly by "Is there a way to install automaticly these dependencies when running the script ?"

And note that our officially supported platforms are only Ubuntu, Debian, Kali Linux, and unofficial support for Fedora.
