### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by mynameisv** [PowerShellEmpire/Empire#155]
Hi,
i've got a bug in the http.py file : 

 `(Empire: agents)  >
----------------------------------------
Exception happened during processing of request from ('10.13.37.10', 40250)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/tmp/empire/lib/common/http.py", line 114, in do_POST
    length = int(self.headers.getheader('content-length'))
TypeError: int() argument must be a string or a number, not 'NoneType'
----------------------------------------`
I think it could be resolved with this lines : 
        # read in the length of the POST data
        if self.headers.getheader('content-length') is None:
        	length = 0
        	postData = ''
        else:
        	length = int(self.headers.getheader('content-length'))
        	postData = self.rfile.read(length)

Best regards.

**Comment by enigma0x3** [comment]
What are you doing when it bug shows?

**Comment by mynameisv** [comment]
Nothing, it continues to work (seems to work ^_^).
But to be secure, i just exit and start empire again :-)

**Comment by HarmJ0y** [comment]
Thanks, we'll have a fix incoming this week with a new branch push.

**Comment by HarmJ0y** [comment]
The fix for this should be in the dev branch https://github.com/PowerShellEmpire/Empire/commit/ce307aa6dba70ef1b1d9119991c221f530e0e75e

I'm going to go ahead and close this issue, if there's a problem again feel free to reopen or comment.
