### ISSUE TITLE
Active Listeners issue 

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#156]
Active Listeners shows 0
Yet, there is 1 listener active

Please see attached screenshot for reference.

![nameandactive](https://cloud.githubusercontent.com/assets/17691989/13885276/9e3b8eb2-ed42-11e5-9b6b-81e947c52004.PNG)

**Comment by enigma0x3** [comment]
If you kill the server and bring it back up, does it update?

**Comment by mattifestation** [comment]
That's some quality OPSEC revealing your target IP. :stuck_out_tongue:

**Comment by honeyfairy** [comment]
Sorry, by kill the server, do you mean restart empire or restart the server? 

lol... Excellent OPSEC, i should take more care, can't multitask, I was taking photos of myself while doing this

**Comment by enigma0x3** [comment]
Restart Empire

**Comment by honeyfairy** [comment]
If you restart Empire, it shows. It happens randomly

**Comment by HarmJ0y** [comment]
Are you running multiple Empire controllers on the same machine by chance?

**Comment by HarmJ0y** [comment]
We'll close this out in the next few days if there is no response.
