### ISSUE TITLE
Empire freezes after upgrade

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#170]
## Empire Version
March 11 commit - 45d219e1f5e50dd9b10e4442aecbb26f1df7650c

## OS Information (Linux flavor, Python version)
Ubuntu - 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
List the agents

## Screenshot of error, embedded text output, or Pastebin link to the error
```
       163 modules currently loaded

       1 listeners currently active

       5 agents currently active


(Empire) > agents

[*] Active agents:

  Name               Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------          -----------     ------------    ---------           -------             -----    --------------------
[!] Exception: need more than 29 values to unpack
```

After this Empire was just frozen

**Comment by enigma0x3** [comment]
Were these agents active before the update?

**Comment by mubix** [comment]
@enigma0x3 yes, and yes

**Comment by enigma0x3** [comment]
This is likely due to the fact that the update included a backend database change. See http://www.harmj0y.net/blog/empire/empire-1-5/ for details.
