### ISSUE TITLE
index in Listener's DefaultProfile setting

### ISSUE THREAD

**Issue by Ne0nd0g** [PowerShellEmpire/Empire#178]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Kali Rolling x64
Python 2.7.11

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

1. Create a listener that uses an 'index.aspx' page in its DefaultProfile like:
```set DefaultProfile /admin/get.php,/index.aspx,/login/process.jsp|Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko```

it will trigger on directories too; like /testing/index.aspx
2. Generate listener, usestager launcher, set Listener, generate
3. Run the powershell command and 1 agent will check in. The agent will only check in once
4. Run the same powershell command again and again;  no new agents will check in.
 
## Any additional information
Thanks for building this product, I enjoy using it.

**Comment by HarmJ0y** [comment]
Good catch, confirmed. Likely some kind of conflict with the stage0/stage1/stage2 staging URIs that utilize 'index'. I'll try to dive into this today.

**Comment by HarmJ0y** [comment]
This should be fixed in the dev branch with https://github.com/PowerShellEmpire/Empire/commit/f699ec510d43b0a760e58aa1f7c41f29c688d8be

If you still encounter an issue, feel free to reopen this issue. Thanks!
