### ISSUE TITLE
No module named Crypto.Random 

### ISSUE THREAD

**Issue by forkmind** [PowerShellEmpire/Empire#179]
## Empire Version
1.5

## OS Information (Linux flavor, Python version)
Ubuntu 14.04 (64 bits)

## Screenshot of error, embedded text output, or Pastebin link to the error

./install.sh
<pre>
`Traceback (most recent call last):
  File "./setup_database.py", line 4, in <module>
    from Crypto.Random import random
ImportError: No module named Crypto.Random`</pre>
cd ../ && ./empire
<pre>`Traceback (most recent call last):
  File "./empire", line 4, in <module>
    from flask import Flask, request, jsonify, make_response, abort
ImportError: No module named flask`</pre>

## Any additional information

Fresh install of Ubuntu  

## Edit: 
It seems that pip is not installed by default on Ubuntu (at least 14.04). For others experiencing the same issue just do an `apt-get install python-pip` before launching the setup.

**Comment by forkmind** [comment]
Fixes #179

**Comment by enigma0x3** [comment]
Ubuntu isn't technically "supported" as of right now. We will look at adding this into the setup script and adding support for it.

Thanks!
