### ISSUE TITLE
Feature Request: Kerberoast

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#183]
So a couple things:

- [ ] Fix/make export of kerberos tickets module (Mimikatz has the ability to export the tickets in base64 instead of binary so it can actually be opsec safe. Right now when you use the Mimikatz command module to export tickets in Empire they get dumped to System32
- [ ] Make an all-in-one kerberoast module that pulls all the SPNs, finds the ones that are just users (not computers or krbtgt / kadmin) and requests the tickets using powershell, then dumps them via Base64 and stores them on the attacker/empire box in Kirbi format with the username of the service (this is important since it's not in the ticket itself, only in the SPN, thx @nidem for the clarification), computer of the service, and the service name .kirbi so that i can be crack
- [ ] Possibly take this one step further and use the code from the kirbi2john to just export it in John format

for reference:
Tim Medin - @nidem
Talk Video: https://www.youtube.com/watch?v=PUyhlN-E5MU
Talk Slides: https://files.sans.org/summit/hackfest2014/PDFs/Kicking%20the%20Guard%20Dog%20of%20Hades%20-%20Attacking%20Microsoft%20Kerberos%20%20-%20Tim%20Medin(1).pdf

**Comment by nidem** [comment]
I have a PowerShell script to get tickets for user accounts that can be incorporated here: https://github.com/nidem/kerberoast/blob/master/GetUserSPNs.ps1

**Comment by HarmJ0y** [comment]
PowerView already had the ability to search for users with non-null SPNs, so I added a quick function that requests the tickets so you can do "Get-NetUser -SPN | Request-SPNTicket". This is now implemented in the *credentials/get_spn_tickets module*.

*credentials/mimikatz/extract_tickets* was also added to extract out current kerberos tickets from memory and output to Empire in base64 form. Both of these modules are in this commit- https://github.com/PowerShellEmpire/Empire/commit/b977dec1ae71753b6b896497be222abc6a124639

At this point, we're not going to auto-extract out the tickets and save to disk, but may revisit at some point down the road.
