### ISSUE TITLE
Macro and VBS stagers not working on Windows 10

### ISSUE THREAD

**Issue by forkmind** [PowerShellEmpire/Empire#185]
## Empire Version
1.5

## OS Information (Linux flavor, Python version)
Ubuntu 14.04

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Macro and VBS stagers never call back to the server. I cannot provide any logs/errors as Empire never send the stage 1. The version of Office used is Office 2016 and the macro is contained in an Office 2003 document. 

## Screenshot of error, embedded text output, or Pastebin link to the error
The agent is never created.

## Any additional information
I could have open an other issue for the VBS stager but I think there are somme chances the two issues are related: the launcher and laucher.bat works well and those two (VBScript and Macro) stagers use VBScript. 

WSH is enabled (when I double click on the VBScript stager, a pop up for confirming is opened) and I can see a powershell process running (just check for VBScript though) which wasn't there before running the script so I don't see the origin of the issue. 

The stagers are generated using default settings.
Does anyone else have the same issue on win 10 ?

**Comment by enigma0x3** [comment]
Interesting, let me get a Win10 vm stood up and I will test this.

Thanks!

**Comment by HarmJ0y** [comment]
I unfortunately don't have a Win10 box with office installed, so I can't track it down personally.

**Comment by enigma0x3** [comment]
I just tested the vbs stager and it works on my win10 image. Do you get any errors when executing? Can you check the process listing and see if powershell.exe is running?

Also, can you try to execute a normal stager and see if it registers?

Thanks!

**Comment by HarmJ0y** [comment]
If we can't recreate we'll unfortunately have to close the issue out.

**Comment by davgit2** [comment]
@enigma0x3 A powershell.exe process is running ; I don't have any errors in Empire as the stage 0 is never sent so nothing is detected on the attacker side; the normal stager and launcher.bat works well. Do you have Windows Defender enabled ? I though it was an effect of [security changes in Windows 10 concerning Powershell] (https://blogs.msdn.microsoft.com/powershell/2015/06/09/powershell-the-blue-team/) (pretty sure you've already read it but I post it anyway).
