### ISSUE TITLE
agents > list tab completion not working

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#186]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Linux kali 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux
Python 2.7.11+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Discovered this testing the 'list stale' command. Typed 'list', SPACE, TAB. No options listed. Remove stale works

## Screenshot of error, embedded text output, or Pastebin link to the error
n/a

**Comment by enigma0x3** [comment]
hey @leesoh,
There is currently a fix in the dev branch: https://github.com/PowerShellEmpire/Empire/commit/dce67beaeb31faf825202922460d372d89a5523a

Feel free to check that out. Once we fix a few more issues, we are going to merge them all into master.

Thanks!

**Comment by timothyleung** [comment]
Having the same issue on MAC 10.11.6

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
@timothyleung I think you have more chance with #475 that with this closed issue
