### ISSUE TITLE
Empire install 

### ISSUE THREAD

**Issue by phonixnoir** [PowerShellEmpire/Empire#191]
## OS Information (KALI Linux, Python version : 2.37.11+)

Hello ,
I wanted to test the Empire code, so I followed the step instalation described on the website and when I demarer the code by typing "./empire" I find myself with a message derreur "

##  i get this message 
Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/root/Téléchargements/Empire-master/lib/common/empire.py", line 22, in <module>
    import http
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 53, in <module>
    class RequestHandler(BaseHTTPRequestHandler):
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 59, in RequestHandler
    serverVersion = helpers.get_config('server_version')[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

## no additional information
thank you in advance for the work provided

**Comment by HarmJ0y** [comment]
Can you add this right above line 59 in ./lib/common/http.py:

`print helpers.get_config('server_version'); import sys; sys.exit();`

then run ./empire again and tell us what the output is?

Also, did you run ./setup/install.sh ? Also try running ./setup/reset.sh to see if that makes a difference.

**Comment by phonixnoir** [comment]
hi,

I used " ./setup/reset.sh " and that works well , 
I will start to try Empire .

thanks alot for your answer
