### ISSUE TITLE
Feature Request: Agent Actions on Check-In

### ISSUE THREAD

**Issue by bneg** [PowerShellEmpire/Empire#195]
Agent actions on initial check-in.

Would work similar to Cobalt Strike. Agent checks in for the first time and is given an immediate task, likely via management/invoke_script or even one of the other canned modules.

Would be best to have as part of Empire itself, but the other way I thought about doing it was via the new REST API.

**Comment by HarmJ0y** [comment]
This was implemented back in November as a fix to issue #80 , which explains the implementation in more detail.

**Comment by bneg** [comment]
Well shit. Thanks for setting me straight. And thank you for making this feature.

**Comment by HarmJ0y** [comment]
No problem! Hopefully it's useful.
