### ISSUE TITLE
Initial Agent active Time

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#201]
## Empire Version
Latest (today)

## OS Information (Linux flavor, Python version)
Kali 64 Latest 

How do I know the time when the Initial agent became active?

Perhaps a temporary workaround for this would be if I could edit the script to automatically do a ` agents > list` command as soon as any agent becomes active, as the list of agents shows the Last Seen time.
But, I don't have the necessary skills to do the above modification, perhaps some help? 
Or would this be accepted as a feature request?

**Comment by HarmJ0y** [comment]
When the agent checks in it displays a message to the main UI, and if you want to know the original checkin time, you can:

```
(Empire: agents) > interact AGENTID
(Empire: AGENTID) > info
```

and it will display the original checkin time under the "checkin_time" field.
