### ISSUE TITLE
Error after starting RESTful API

### ISSUE THREAD

**Issue by leebaird** [PowerShellEmpire/Empire#203]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Kali 2.0
```
./empire --rest --restport <port> --headless --username <username> --password <password>
```

[*] Loading modules from: /opt/Empire/lib/modules/
 * Starting Empire RESTful API on port: 443
 * RESTful API token: kvru3y7ltipp21tjeu3lduy05wua9ahwaodzfntw
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Logged from file _internal.py, line 87

**Comment by HarmJ0y** [comment]
I wasn't able to recreate and can't decode the exact issue from the output, but the options were being used incorrectly (i.e. --username requires a value, --rest/--headless being mutually exclusive).

This commit to dev https://github.com/PowerShellEmpire/Empire/commit/37f129fe8198e90e7bff73001823b878113e978a tightened up the argument parsing validation and should be more clear.

**Comment by leebaird** [comment]
Sorry, I forgot to place that command line in quotes and it stripped away the GT and LT signs.

**Comment by HarmJ0y** [comment]
@enigma0x3 can you check this out on your Kali test VM?

**Comment by HarmJ0y** [comment]
So I downloaded the latest Kali 2.0 VM from https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/ , updated, cloned Empire, checked out the dev branch, and ran its installer. I wasn't able to recreate the issue:

<img width="787" alt="rest_error" src="https://cloud.githubusercontent.com/assets/5504523/15089234/1e9134c6-13b4-11e6-87d1-f9577e67f8ed.png">

**Comment by leebaird** [comment]
Try port 443.

**Comment by HarmJ0y** [comment]
<img width="725" alt="empire_rest_443" src="https://cloud.githubusercontent.com/assets/5504523/15090226/7b6f794e-13d4-11e6-9452-613ac41e0ffb.png">

Do you have apache running on the system by chance?

**Comment by leebaird** [comment]
I pulled down a new copy of Empire and that seems to have resolved the issue. I appreciate your time.

**Comment by HarmJ0y** [comment]
Sounds good.
