### ISSUE TITLE
Problems with port forwarding in listener options

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [PowerShellEmpire/Empire#204]
Hi guys,

I have a problem with the `Port` and `Host` options in the listeners module only. Indeed it is not possible to set a different port value in these two options.
For example, I need my listener binds on `192.168.1.1:1337` but I also want agents connect back to `http://example.com:80`, the PAT/NAT is operated by my firewall.
The problem is, when I set a port in `Host` option, the `Port` option is automatically modified and vice versa.
Is it possible to totally separate these options in the next release ?

Thanks for this awesome tool by the way ;)

**Comment by HarmJ0y** [comment]
We'll check into this, thanks for the heads up.

**Comment by HarmJ0y** [comment]
This won't be an easy change, and as we're unsure as to when we'd be able to implement it, I'm going to close out this issue for now.

For a workaround, you can set the regular listener that binds on your local host, and then use a "**foreign**" listener (which just doesn't bind to an actual port) to specify domain.com:80 as the C2 domain. Then generate the stagers for the foreign listener config. A bit more information: http://www.powershellempire.com/?page_id=145

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I tried the workaround today and I can confirm it works like a charm. Thanks for the tip ;)

**Comment by mubix** [comment]
@ThePirateWhoSmellsOfSunflowers I was able to get this same thing to work by starting a normal listener, shutting down Empire, then modifying the SQLite database and starting Empire back up. Like so:

Run on port 2443:
```
(Empire) > listeners
(Empire: listeners) > set Name rev
(Empire: listeners) > set CertPath ../data/empire.pem
(Empire: listeners) > set Host https://104.236.49.208
(Empire: listeners) > set Port 2443
(Empire: listeners) > run
```

Modify to generate payloads/launchers for 443:
```
root@oneport:/opt/empire/data# sqlite3 empire.db
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints
sqlite> update listeners set host='https://104.236.49.208' where name='rev';
sqlite> .q
root@oneport:/opt/empire/data#
```

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Dirty hack but if it works... :) So in this case, why not remove directly these lines ?
https://github.com/PowerShellEmpire/Empire/blob/master/lib/common/listeners.py#L218#L220
https://github.com/PowerShellEmpire/Empire/blob/master/lib/common/listeners.py#L176
https://github.com/PowerShellEmpire/Empire/blob/master/lib/common/listeners.py#L189#L191

I do not know if such changes may cause other bugs, but if your technique works maybe it's worth to try.

**Comment by qbiguenet** [comment]
We can't set the listeners type to "foreign" anymore ?
What should we do now ?

**Comment by xorrior** [comment]
@qbiguenet the listener type is http_foreign
