### ISSUE TITLE
Empire Powershell loses connection with agents

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#206]
## Empire Version
Did a `git pull origin dev ` yesterday

## OS Information (Linux flavor, Python version)
Kali 64

I've had a couple of agents active for around 6 or 7 hours. and suddenly Empire Powershell loses interaction with all of them, I tried running the launcher code from another machine, but it doesnt receive the initial agent too.

What could be the issue?

**Comment by honeyfairy** [comment]
An update on this.
A restart of the server fixes the issue.
After I restart, then Empire powershell is active again.

How would I go about debugging this issue?

Also, how do I fully restart Empire Powershell? Just exit and start it again?

If I try to exit, it just hangs, like:
`(Empire: agents) > exit

[>] Exit? [y/N] y

[!] Shutting down...


`

**Comment by HarmJ0y** [comment]
Launch "./empire --debug" to output debug info to ./empire.debug, or "./empire --debug 2" to also output the same debug info to the screen. Ctrl + c and confirmation is probably the best way to stop/restart Empire.
