### ISSUE TITLE
Whats the difference if I leave the stale agents or remove them?

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#207]
If i do a `remove stale` command, does this mean that the next time the agents computer comes online, will I get another _Initial agent_ callback?

In other words, is there any benefit in leaving the stale agents listed?

**Comment by mubix** [comment]
In my experience, if you have run something that takes a long time and is "blocking" it will not be checking back in. I have accidentally removed agents like this many times, and when they finally do call home it doesn't start up a new agent. So I would say, in my experience "no". But I would love if it worked the way you say so, or if there was a way to set up things to do it that way

**Comment by honeyfairy** [comment]
So, its better to leave the stale agents listed. Correct?

**Comment by HarmJ0y** [comment]
I would, but we wanted to have the option to clear things out if people wanted. Mubix is correct that at this point there's no orphaned reconnect- that's on the general dev plan at some point.
