### ISSUE TITLE
Autorun issue. Only one module autoruns,

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#210]
## Empire Version
Latest Dev

## OS Information (Linux flavor, Python version)
Kali 64 Latest

References: 
#80 
#195 

Issue:
Only one module autoruns, even if I execute 2 or more modules as `autorun`

For example, I executed collection/keylogger as autorun, then i executed collection/screenshot as autorun. When an agent checks in, only the screenshot runs, not the keylogger.
Whichever module I execute last works.

**Comment by HarmJ0y** [comment]
The architecture is only meant to run one module as an autorun at this point. If you want multiple modules to autorun, you can build out the script logic you want to run and use **management/invoke_script** to input the new combined script and set it to autorun.

**Comment by honeyfairy** [comment]
Thank you, were could I find a guide on how to write a simple script? For eg, just to start both keylogger and screenshot.
I have searched, but couldnt get the info i needed to start
