### ISSUE TITLE
Keylog does not log every keystroke

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#212]
## Empire Version
Latest Dev

## OS Information (Linux flavor, Python version)
Kali 64

Notice what I typed and the logs on the screenshot below

## Screenshot of error, embedded text output, or Pastebin link to the error
![keylogerror](https://cloud.githubusercontent.com/assets/17691989/15074085/a9ce0df2-13a5-11e6-99ec-8105d1d7dd25.PNG)

**Comment by HarmJ0y** [comment]
This is a known limitation with PowerSploit's existing Get-KeyStrokes module https://github.com/PowerShellMafia/PowerSploit/issues/50
