### ISSUE TITLE
Access is denied  persistence/elevated/schtasks

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#213]
## Empire Version
Latest Dev

## OS Information (Linux flavor, Python version)
Kali 64

I have system, via bypassuac, other elevated modules work fine.
Target PC is Windows 10 64bit, running 360 Total Security and Windows Defender
```
(Empire: persistence/elevated/schtasks) > execute
[>] Module is not opsec safe, run? [y/N] y
(Empire: persistence/elevated/schtasks) >
error running command: Program 'schtasks.exe' failed to run: Access is deniedAt line:1 char:1411
+ ... gAnACcAKQA=;schtasks /Create /F /RU system /SC ONIDLE /I 10 /TN 360_T ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.

(Empire: persistence/elevated/schtasks) >
```

**Comment by enigma0x3** [comment]
From that agent, can you verify that you are elevated?

**Comment by honeyfairy** [comment]
Yes, an asterisks shows on the agent name, and `persistence/elevated/registry `works

**Comment by enigma0x3** [comment]
Can you do a "whoami /groups" and see what integrity you are?

**Comment by HarmJ0y** [comment]
Please let us know the results of the above command- we'll close the issue within a week or so of no response.

**Comment by enigma0x3** [comment]
Hey @honeyfairy,
Going to go ahead and close this. I recommend running "whoami /groups" and checking what integrity you are in.

Thanks!
