### ISSUE TITLE
? Scripts?

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#214]
Where could I find a guide on how to write a simple script for use with **management/invoke_script**? For eg, just to start both keylogger and screenshot.
I have searched, but couldnt get the info i needed to start

I dont understand, should the script.ps1 be on the target machine before the invoke script command is run? 

Any help will be highly appreciated

**Comment by HarmJ0y** [comment]
So script sources are kept in https://github.com/PowerShellEmpire/Empire/tree/master/data/module_source , any if you launch empire with `--debug`, **./LastTask.ps1** will contain the last tasked PowerShell script with options.
