### ISSUE TITLE
Issue with MiniEye

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#217]
## Empire Version
Latest Dev

## OS Information (Linux flavor, Python version)
Kali Rolling 2016 64bit

I'm in a medium integrity process, when i do a `collection/MiniEye` i get the following output
`Output saved to ./downloads/xxxxxxxxxxxxxxxxx/error running c/2016-05-10_01-25-46.omman`
The .omman file is 65 bytes, and does not play as a video

Please advise

**Comment by HarmJ0y** [comment]
What are the details for the target OS?

@xorrior - if you're able to test or chime in let us know (he's the original module author).

**Comment by honeyfairy** [comment]
I have tested it on Windows Vista Business x86 and Windows 7 x64 Pro, test done on 3 computers, Same issue with all.

**Comment by xorrior** [comment]
Are these systems VM's or physical machines? Also, are these built-in webcams or usb? I'll try to test it on those systems. Haven't seen that before in the testing I've done.

**Comment by honeyfairy** [comment]
They are physical laptops with built in webcams.
Please update us once you have checked it out, much appreciated.

**Comment by HarmJ0y** [comment]
Ping @xorrior - were you able to get an opportunity to check into this by chance?

**Comment by xorrior** [comment]
Sorry, this slipped into the cracks. I'll test it out today.

**Comment by xorrior** [comment]
Tested it out, looks like its an issue with how the module code is being put together. Ran empire in debug mode, here is the snapshot. 
![minieye-issue](https://cloud.githubusercontent.com/assets/9156069/15628774/1b722626-24d8-11e6-8895-a024788599c5.png)

**Comment by enigma0x3** [comment]
@xorrior any luck on figuring out what was causing the function to break like that?

**Comment by HarmJ0y** [comment]
Ping @xorrior in case there was any progress.

**Comment by xorrior** [comment]
My best guess was maybe it is how the script was being put together client side? Not sure exactly

**Comment by xorrior** [comment]
I'll try testing it out again and see what happens

**Comment by xorrior** [comment]
Fixed in my latest pull.

**Comment by enigma0x3** [comment]
@honeyfairy,
This should be fixed now if you do a pull from the dev branch.

@xorrior, thanks for fixing this :)
