### ISSUE TITLE
management/invoke_script Clarification 

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#218]
I'm building a script to get screenshots and log keystrokes. Then have it autorun upon Initial agent becoming active.
1) To clarify, do i just  copy the scripts that i need and pasting it below each other into one **allscripts.ps** file? Like this: http://pastebin.com/j2pm7Wvn ?
2) What should the options be of  `ScriptCmd` (of `management/invoke_script` module)

The Description says: `Script command (Invoke-X) from file to  run,`
But I dont quite understand, perhaps an example please?

**Comment by honeyfairy** [comment]
I have tried the following values for ScripCmd:
**Invoke-Command 
Invoke-Expression 
Invoke-Item**

But it does not work. The .ps1 script is a screenshot script but I dont get a screenshot.

Here is a log of what I am doing:
http://pastebin.com/iXiQjQiX

**Comment by HarmJ0y** [comment]
**invoke_script** just takes a script block and pastes the specified ScriptCmd at the end. An example of a simple module would be https://github.com/PowerShellEmpire/Empire/blob/dev/data/module_source/management/Invoke-RunAs.ps1 , and the **ScriptCmd** would be something like **'Invoke-RunAs -username john...'**. 

If you have additional questions on PowerShell development I would recommend asking in the #psempire channel on Freenode.
