### ISSUE TITLE
privesc/powerup/service_stager shows False at the end

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#219]
## Empire Version
Latest Dev

## OS Information (Linux flavor, Python version)
Kali 2016 64

Does `False` below indicate that it was unsuccessful? 

```
(Empire: privesc/powerup/service_stager) > execute
[>] Module is not opsec safe, run? [y/N] y
(Empire: privesc/powerup/service_stager) >
Job started: Debug32_tuyka

Launcher bat written to C:\Users\dts_user\AppData\Local\Temp\debug.bat
False

```

**Comment by HarmJ0y** [comment]
That means that something failed.

I added more verbose output for that command in this commit https://github.com/PowerShellEmpire/Empire/commit/0fb6599c7704ab2b6bf1359d9a43cb40c5021e16 which should give you more information if you rerun.
