### ISSUE TITLE
Missing a way to get the handlers from the api it self

### ISSUE THREAD

**Issue by tristandostaler** [PowerShellEmpire/Empire#222]
I modified a little bit the "empire" python file with the following content to make it work. I just tought it would be a nice to have!

def start_restful_api(startEmpire=False, suppress=False, username=None, password=None, port=1337):
"""
(...)
"""

    handlers = '''
GET,http://localhost:1337/api/version,return the current Empire version

GET,http://localhost:1337/api/config,return the current default config

GET,http://localhost:1337/api/stagers,return all current stagers
GET,http://localhost:1337/api/stagers/X,return the stager with name X
POST,http://localhost:1337/api/stagers,generate a stager given supplied options (need to implement)

GET,http://localhost:1337/api/modules,return all current modules
GET,http://localhost:1337/api/modules/<name>,return the module with the specified name
POST,http://localhost:1337/api/modules/<name>,execute the given module with the specified options
POST,http://localhost:1337/api/modules/search,searches modulesfor a passed term
POST,http://localhost:1337/api/modules/search/modulename,searches module names for a specific term
POST,http://localhost:1337/api/modules/search/description,searches module descriptions for a specific term
POST,http://localhost:1337/api/modules/search/description,searches module comments for a specific term
POST,http://localhost:1337/api/modules/search/author,searches module authors for a specific term

GET,http://localhost:1337/api/listeners,return all current listeners
GET,http://localhost:1337/api/listeners/Y,return the listener with id Y
GET,http://localhost:1337/api/listeners/options,return all listener options
POST,http://localhost:1337/api/listeners,starts a new listener with the specified options
DELETE,http://localhost:1337/api/listeners/Y,kills listener Y

GET,http://localhost:1337/api/agents,return all current agents
GET,http://localhost:1337/api/agents/stale,return all stale agents
DELETE,http://localhost:1337/api/agents/stale,removes stale agents from the database
DELETE,http://localhost:1337/api/agents/Y,removes agent Y from the database
GET,http://localhost:1337/api/agents/Y,return the agent with name Y
GET,http://localhost:1337/api/agents/Y/results,return tasking results for the agent with name Y
DELETE,http://localhost:1337/api/agents/Y/results,deletes the result buffer for agent Y
POST,http://localhost:1337/api/agents/Y/shell,task agent Y to execute a shell command
POST,http://localhost:1337/api/agents/Y/rename,rename agent Y
GET/POST http://localhost:1337/api/agents/Y/clear,clears the result buffer for agent Y
GET/POST http://localhost:1337/api/agents/Y/kill,kill agent Y

GET,http://localhost:1337/api/reporting,return all logged events
GET,http://localhost:1337/api/reporting/agent/X,return all logged events for the given agent name X
GET,http://localhost:1337/api/reporting/type/Y,return all logged events of type Y (checkin, task, result, rename)
GET,http://localhost:1337/api/reporting/msg/Z,return all logged events matching message Z, wildcards accepted

GET,http://localhost:1337/api/creds,return stored credentials

GET,http://localhost:1337/api/admin/login,retrieve the API token given the correct username and password
GET,http://localhost:1337/api/admin/permanenttoken retrieve the permanent API token, generating/storing one if it doesn't already exist
GET,http://localhost:1337/api/admin/shutdown,shutdown the RESTful API
GET,http://localhost:1337/api/admin/restart,restart the RESTful API
'''

(...)

    @app.route('/api/handlers', methods=['GET'])
    def get_handlers():
        """
        Returns all the available handlers
        """
        return jsonify({'Handlers':handlers})

Could probably be better but it was made quick for a tool.

**Comment by tristandostaler** [comment]
Just found this. Might help!

http://stackoverflow.com/questions/13317536/get-a-list-of-all-routes-defined-in-the-app

**Comment by HarmJ0y** [comment]
Sorry, I'm confused as to exactly what you're saying here, edited "with the following content to make it work"? Do you mean the API wasn't working for you?

If you had a code modification, a pull request is probably the best option.

**Comment by tristandostaler** [comment]
Sorry if I wasn't clear. What I meant is that with the command line, you can always do "help" to get all the available options.
The API is working fine, but it is not possible to get all the possible handlers (or routes) without going in the source code to see the comment with them. 
So my idea would be to add some way for the API to provide the handlers (a bit like a WSDL).
I tought that one way would be to call "/api/handlers" and it would awnser with something like what I put in the variable "handlers" in my original comment.
Then I saw that there is a way to make it more dynamical and provided a stackoverflow.com link.

Also, I am not sure what is the best way to do it so I figured I would give my idea as an issue so someone better than me could do it.

Thanks for your reply!

**Comment by tristandostaler** [comment]
I found a solution. I will make a pull request soon.
