### ISSUE TITLE
Python stager

### ISSUE THREAD

**Issue by goldenbr0wn** [PowerShellEmpire/Empire#224]
A python stager would be very cool to intergrate in scripts/executables. I have tried to pass the launcher string to powershell.exe from python but with no success and it doesn't seems to be the most elegant solution.

**Comment by HarmJ0y** [comment]
I don't really see what the point is here -> "pass the launcher string to powershell.exe from python"? What are you exactly trying to accomplish?

**Comment by goldenbr0wn** [comment]
>Why not just call the powershell.exe launcher directly?

This is exactly what I want to accomplish using something like subprocess.call or subprocess.Popen (e.g. subprocess.call('taskkill /F /IM exename.exe')) but instead pass it a string to launch a powershell launcher.

**Comment by HarmJ0y** [comment]
What I mean is that in that since you're already running Python, why not just run the PowerShell launcher originally? In what realistic context are you going to have Python running where you wouldn't have been able to just launch powershell.exe?

**Comment by goldenbr0wn** [comment]
> In what realistic context are you going to have Python running where you wouldn't have been able to just launch powershell.exe?

In a situation when the user writes and uses python scripts regularly - if the file seems legit and contains many instructions, a malicious portion could remain unnoticeable at first sight. But yes, Powershell.exe is available, the thing is to launch an agent from a python script without being too noisy.

**Comment by HarmJ0y** [comment]
I ran the launcher with **import os; os.system('powershell.exe ...')** without much issue. We're going to close this for now but will reconsider it at some point again going forward.
