### ISSUE TITLE
Plugins for Empire ?

### ISSUE THREAD

**Issue by goldenbr0wn** [PowerShellEmpire/Empire#225]
The API is awesome for doing API requests to an Empire server from an other soft, but I am seeking for Empire to perform an action when something happen, to script his behavior (in this case to use the [Pushover API](https://pushover.net/faq#library-python)).
I have already wrote a monkey solution for myself in `lib/common/empire` that works, but it's hardcoded and only alert for incoming and exiting agents.
Before doing anything I just wanted to know the vision you (the developers) have for this tool and wether you find it relevant to have a way to interact with Empire itself through "plugins".

**Comment by HarmJ0y** [comment]
So it's not on our roadmap to implement something like this in the next several months. Feel free to reopen the issue a bit down the road for reconsideration.

**Comment by goldenbr0wn** [comment]
Thanks for the answer

**Comment by DakotaNelson** [comment]
Hi all: I'm currently hacking on this, and expect to have something worth looking at by the end of the week.

**Comment by DakotaNelson** [comment]
Just kidding, somehow I really got into it and 3 hours later here we are; submitting a PR now.
