### ISSUE TITLE
socket.gethostbyname(socket.gethostname()) can throw exception

### ISSUE THREAD

**Issue by tomsteele** [PowerShellEmpire/Empire#23]
https://github.com/PowerShellEmpire/Empire/blob/3cedb106a999c5f443e68952f65abb4b44ea3033/lib/common/helpers.py#L364

```
socket.gethostbyname(socket.gethostname())
```

Can throw:
```
socket.gaierror: [Errno -2] Name or service not known
```

Best case is to probably wrap in try/except and proceed into the block of logic below:
```
    if ip.startswith("127.") and os.name != "nt":
        interfaces = ["eth0","eth1","eth2","wlan0","wlan1","wifi0","ath0","ath1","ppp0"]
        for ifname in interfaces:
            try:
                ip = get_interface_ip(ifname)
                if ip != "":
                    break
            except:
                print "Unexpected error:", sys.exc_info()[0]
                pass
```

**Comment by HarmJ0y** [comment]
This look correct? https://github.com/PowerShellEmpire/Empire/commit/b434102f2c2275eaf2e56825014d8b0be3d3190c

**Comment by tomsteele** [comment]
@HarmJ0y was thinking something like this:

```
    ip = ""
    try:
        ip = socket.gethostbyname(socket.gethostname())
    except socket.gaierror:
        pass
    except:
        print "Unexpected error:", sys.exc_info()[0]
    	return ip

    if (ip == "" or ip.startswith("127.")) and os.name != "nt":
    	interfaces = ["eth0","eth1","eth2","wlan0","wlan1","wifi0","ath0","ath1","ppp0"]
        for ifname in interfaces:
        	try:
            	ip = get_interface_ip(ifname)
            	if ip != "":
                	break
                except:
                    print "Unexpected error:", sys.exc_info()[0]
                    pass
    return ip
```

This way we can set to the ip of the interface if we run into the name error. About to get on a plane, I have no idea if this code runs :smile. But you get the idea.

**Comment by HarmJ0y** [comment]
sure, if you don't mind doing the pull that'd be sweet, just to ensure it's broken up/runs how you're envisioning

**Comment by HarmJ0y** [comment]
Cool, code works https://github.com/PowerShellEmpire/Empire/commit/54c7300998f13730f17ba3d270ee45bd9c28fa9e 

If there are any additional issues with it let us know, this branch will be merged in within the next few days.
