### ISSUE TITLE
PowerShell 2.0 incompatible module

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#230]
Get-SPN uses "ordered" which is a [PowerShell 3.0+ only feature](http://stackoverflow.com/questions/7802406/use-cases-of-ordered-the-new-powershell-3-0-feature). This means that the module errors out and does not return anything when run on PowerShell 2.0 only hosts:

https://github.com/PowerShellEmpire/Empire/blob/master/data/module_source/situational_awareness/network/Get-SPN.ps1#L195

**Comment by HarmJ0y** [comment]
Thanks for the catch, should be fixed with https://github.com/PowerShellEmpire/Empire/commit/e0802fb6d104396a5487c8a0fcd1fe555fb9cdbd
