### ISSUE TITLE
management runas module error

### ISSUE THREAD

**Issue by juushya** [PowerShellEmpire/Empire#232]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Running Empire on Ubuntu 12.04 x64
Python 2.7.3
Command executed on - Microsoftr Windows Serverr 2008 Enterprise, 6.0.6002 Service Pack 2 Build 6002

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Error is thrown when using the module management/runas
Attempting to use domain admin creds to add a new user to DC

## Screenshot of error, embedded text output, or Pastebin link to the error

```
(Empire: management/runas) > info

           Name: Invoke-RunAs
         Module: management/runas
     NeedsAdmin: False
      OpsecSafe: True
   MinPSVersion: 2
     Background: False
OutputExtension: None

Authors:
  rvrsh3ll (@424f424f)

Description:
  Runas knockoff. Will bypass GPO path restrictions.

Options:

  Name       Required    Value                     Description
  ----       --------    -------                   -----------
  UserName   False       dadmin               Username to run the command as.         
  CredID     False       29                        CredID from the store to use.           
  Domain     False       targetdomain              Optional domain.                        
  Cmd        True        'net user                 Command to run.                         
                         newuser    
                         password /add /domain' 
  Agent      True        2REGBMBGWN3UYZKS          Agent to run module on.                 
  ShowWindow False                                 Switch. Show the window for the created 
                                                   process instead of hiding it.           
  Password   False       dadminpass                Password for the specified username.    

(Empire: management/runas) > 
(Empire: management/runas) > 
(Empire: management/runas) > execute
(Empire: management/runas) > 
**[!] Error in runas: Exception calling "Start" with "1" argument(s): "Access is denied"**

```
## Any additional information
Not sure if this module can be or should be used to create a new user on DC. I guess it can be used. If not, please feel free to close the issue.

Thanks.

**Comment by HarmJ0y** [comment]
The runas module was originally meant for process launching/token impersonation so we didn't think about executing commands in this particular way. There's now an **Arguments** parameter for the module with the following commit to dev https://github.com/PowerShellEmpire/Empire/commit/7a47ea358319ea31b0a0eb7ac37be302bc8f4365 - I tested it for your scenario and it worked (user was added).

<img width="826" alt="runas" src="https://cloud.githubusercontent.com/assets/5504523/15616817/db4cdeb6-23fa-11e6-8102-03ceb1291e89.png">

Also, make sure you unset the **CredID** field if you're manually specifying credentials - I imagine this is what was giving you the access is denied error.
