### ISSUE TITLE
Empire doesn't work in non-English environments

### ISSUE THREAD

**Issue by Redfast** [PowerShellEmpire/Empire#24]
When I use the latest empire version on kali 2.0, I get an agent, but I can't do anything with it. No modules work, not even trollsploit/message.
Target=(Windows 8.1, AV disabled, no firewall, language=Dutch)

**Comment by jaredbarez** [comment]
Take a look at issue #11 and report your findings...

**Comment by sixdub** [comment]
Hi! Thanks for the report. We have been told my numerous people that Empire has had issues with non-English settings. We would love to get some info so we can keep testing. Is your locale, language, or keyboard set to Dutch?

**Comment by Redfast** [comment]
language=Dutch
keyboard=Belgian
locale=Belgium

**Comment by sixdub** [comment]
We have definitely confirmed that non-english setups present some issues. We are going to continue to test and work through the kinks and see what we can get worked out. Thanks for helping us out and thank you for your patience!

**Comment by 1njected** [comment]
I figured out that it was the Epoch/counter that got messed up on non-us systems, see fix here:
https://github.com/PowerShellEmpire/Empire/pull/18

**Comment by sixdub** [comment]
Hey @1njected , thanks for the help on tracking this down. I have recreated the issues that people have been experiencing and confirmed your code fixes the issue. I will be accepting the pull request this morning. We are tracking down bugs in other languages and international settings as we did not originally test with various locales. If you discover any other issues, please let us know so we can track them. Again, thanks!

**Comment by jaredbarez** [comment]
I confirm the @1njected fix works in my non-US environment. Thank you

**Comment by jacques-** [comment]
Just tested using using master and fresh kali. Confirmed @injected patch was present, did not work for system with locale set to UK.

Changing locale to US fixes the issue.
