### ISSUE TITLE
Lost Agents after fresh copy

### ISSUE THREAD

**Issue by egycondor** [PowerShellEmpire/Empire#242]
After installing new Empire , actually i lost all my agents when i configured the new fresh copy with same Listener name and IP and Port

So how can i retrieve the old agents if possible , if not how can i mitigate it to be happen again

**Comment by enigma0x3** [comment]
Hey @egycondor,
Did you completely tear down empire (and the listener?). If you tore the listener down when updating and tried to stand up a new one, your old agents won't call back because the new listener will have a different staging key.

**Comment by egycondor** [comment]
thanks, so you mean next time i have to use the old staging key to recover my old agents

**Comment by enigma0x3** [comment]
The old agents won't call back but you should be able to launch new agents with the old stager if you change the staging key back to the old one (and everything else matches up). You can change the staging key by killing Empire, opening empire.db in sqlitebrowser, going to the "browse data" tab, change the "table" to "listeners" and change up the staging key.
