### ISSUE TITLE
Beginner questions

### ISSUE THREAD

**Issue by Kratos120** [PowerShellEmpire/Empire#246]
Hello i am new to empire world and i have many questions but start for this one how to connect an agent if open empire after the victim machine start up? bat file input to start up folder in victim machine when open empire before victim machine start up i have active agent but what hapend open empire after? sorry my english is not very well

**Comment by tristandostaler** [comment]
Are you better in french?

**Comment by Kratos120** [comment]
no comment

**Comment by Kratos120** [comment]
someone else that knows?

**Comment by tristandostaler** [comment]
.... I meen "sorry my english is not very well" and I speek french....

**Comment by tristandostaler** [comment]
Because I can't understand your question... Words are missing and all... So if you speek french, then write it in french so I can help you.

**Comment by Kratos120** [comment]
no i am not speak french ...you speak Greek?

**Comment by tristandostaler** [comment]
Nah sorry. Can you try and explain you question better?

**Comment by Kratos120** [comment]
yes i try ....you have open now empire and the victim open his machine in 60 minutes you have an active agent ok so far? what happent if victim nachine open now and you open empire 60 min after you dont have active agent ....exists some methods to activate the agent?

**Comment by Kratos120** [comment]
someone tell me about a autorun script something like that but i dont know where can i found that and how to use? or some other methods

**Comment by tristandostaler** [comment]
Ok so if I understand correctly, you are asking what happens if the Empire Server is not up when the agent ping back and only up 60 minutes later?

When you create the listener, you can specify "DefaultLostLimit" which is "Number of missed checkins before exiting". You can either put it really High or to 0 for infinite.

To get this information, you write "listeners" in empire's main menu and then "info".

To get more info on how to use Empire, read: http://www.powershellempire.com/

**Comment by tristandostaler** [comment]
And for your autorun script question, you might want to read: http://www.powershellempire.com/?page_id=139

**Comment by Kratos120** [comment]
thank you ....."and only up 60 minutes later?" not only 60 what about for more time? the next day for example?

**Comment by tristandostaler** [comment]
When you create the listener, you can specify "DefaultLostLimit" which is "Number of missed checkins before exiting". You can either put it really High or to 0 for infinite.

**Comment by Kratos120** [comment]
I understand for a new listener ..... for listener have already create can i do something in option now?

**Comment by tristandostaler** [comment]
I am not sure but I don't think so. Try it and give me feed back?
Or you could create a second listener and move your agent to that listener.
I won't explain how to do it but it is something possible.

**Comment by Kratos120** [comment]
ok thank you so much for your help

**Comment by enigma0x3** [comment]
You can either create a new listener or update the "DefaultLostLimit" value in the backend database under the "listeners" tab by opening "empire.db" with sqlitebrowser.
