### ISSUE TITLE
FEATURE REQUEST: Clearing agent db / kill agents who don't phone home

### ISSUE THREAD

**Issue by Viss** [PowerShellEmpire/Empire#253]
I'm on a live gig, and agents are coming and going.
Multiple agents from machines that get imaged, or machines that have a task or another method of persistence to phone home - I have literally hundreds.

'agents 10', though, only shows like 5 actually alive. 
It would be neat to say "Kill all shells that are more than 10 minutes old" and have them go away, because if they're going to phone back home next time the persistence task runs, they'll just come back.

**Comment by mubix** [comment]
This already exists with the command `remove stale`

**Comment by Viss** [comment]
ah, rad, thats helpful!
