### ISSUE TITLE
Question about listener IP 

### ISSUE THREAD

**Issue by HamzaGa** [PowerShellEmpire/Empire#255]
Hi , my question is very simple : 
Does empire supports hacking machines in WAN ? it means can i hack a machine that is not in the same LAN ? 
I'm saying this because in all tutorials that i've watched , the Host ip of the listener is like 192.168.***.*** meanwhile i'm behind a NAT router , my public adress is something like 41.225.***.*** , when i put this adress in Host IP of the listener and i generate a stagger linked to this listener , i do not receive agent when the stagger is executed , but in LAN when i put 192.168.***.*** in the Host IP it works .
Thank you .

**Comment by enigma0x3** [comment]
If you are NAT'd, you will likely need to port forward on the firewall.
