### ISSUE TITLE
Username isn't updated after steal_token

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#257]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Linux HOSTNAME 4.5.0-kali1-amd64 #1 SMP Debian 4.5.5-1kali1 (2016-06-06) x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When stealing a token using the steal_token command, the username doesn't refresh in either the info or agents menus unless you run a sysinfo first.

**Comment by HarmJ0y** [comment]
This should be fixed in dev with https://github.com/PowerShellEmpire/Empire/commit/21893bacde237677947decf22916dc3d2a1a21ed

The sysinfo command is now implicitly called when running steal_token or revtoself.
