### ISSUE TITLE
Feature Request: Global Interact!

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#258]
It'd be wonderful to be able to interact with agents from any menu, rather than having to go agents > interact <blah>. Seems small, but when you have to do it a billion times, it adds up.

Probably not actually a billion. Also, it'd be sweet if "int" was enough to toggle the "interact" command.

**Comment by HarmJ0y** [comment]
This should be implemented with https://github.com/PowerShellEmpire/Empire/commit/c38256ab5c7fab56b12d8c6819825ee542e4d205 - the only place the command doesn't work is from another agent context, to prevent agent menu loops (something we'll address at some point.
