### ISSUE TITLE
Agent Listing and Selection issues

### ISSUE THREAD

**Issue by ChrisTruncer** [PowerShellEmpire/Empire#259]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Debian Stable

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

When creating a new agent, it does not always populate the checked-in agents list.  I've established agents where they are communicating with the Empire server, and I've let the systems sit for about 10 minutes to make sure that there wasn't a delay in comms anywhere.

When attempting to view the agents to pick one to interact, one of two problems arise.

1.  There will be no new checked in agent.  It's as if it never checked in.  I will then completely quit Empire, start it back up, and then the agent(s) are there.

2.  The agent will actually be displayed, and I can tab complete the agent ID when telling Empire to interact with it, however Empire always responds with a "Please enter a valid agent name" error and never lets me select the agent.  The only way to fix this is me also having to completely exit Empire and restart it, then it works perfectly.

**Comment by enigma0x3** [comment]
Can you start empire with the --debug 2 flag and paste the output of "empire.debug"?

Thanks!

**Comment by ChrisTruncer** [comment]
I unfortunately don't have access to this system anymore

**Comment by enigma0x3** [comment]
Ok, if you come across this issue again where we can troubleshoot, feel free to re-comment on this issue or open a new one.

**Comment by at1a5-lxc** [comment]
I meet the same problem.Like ChrisTruncer described,when a new agent come online,it does show its agent name in empire agents,and when i type "interact" and Tab its name shows in command.But the empire responds with a "Please enter a valid agent name" if i execute interact command.Of course,if i exit the empire and restart empire,i can interact with that wired agent again.Another problem is that any command execute in this agent will not show result unless i execute "back" and then "interact " again ,it will show result at this time...

**Comment by xorrior** [comment]
@at1a5-lxc Can you open a new issue and fill out a template. Provided a detailed description with the target OS, Empire branch/version, and host OS. Screenshots and empire --debug 2 output would be greatly appreciated. Thanks
