### ISSUE TITLE
Special Characters in Password

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#261]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Linux HOSTNAME 4.5.0-kali1-amd64 #1 SMP Debian 4.5.5-1kali1 (2016-06-06) x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When using (I believe) runas, we get and error due to a < in the password.

## Screenshot of error, embedded text output, or Pastebin link to the error
`< is saved for future implementation` or something similar. Sorry for lack of detail, was a busy day!

## Any additional information
Thanks for all the other things that DO work in Empire :)

**Comment by enigma0x3** [comment]
When you have a chance, can you verify the module and credential? I just tested with a user account containing the "<" character and was able to use the runas and spawnas modules without an issue.

Thank you!

**Comment by leesoh** [comment]
Hi there - my colleague was the one running into the issue and I think he may have tried both (will find out today), but the password started with <, which may change things for you. Are you enclosing it in quotes, or just putting in the raw password?

**Comment by enigma0x3** [comment]
Just tested with the "<" at the beginning of the password and was able to reproduce. As a workaround, you can place the password in quotes and it will work as expected. We will look at forcing quoting around module options, but for now, placing it in quotes should do the trick.
