### ISSUE TITLE
Redirector management module issue

### ISSUE THREAD

**Issue by spivi** [PowerShellEmpire/Empire#266]
Hello,
during a pentest I encountered a situation where the redirector module for pivoting is not working (the portproxy command did not do anything on the target machine).
I came to realize that it was because the windows service iphlpsvc was disabled.
I added to the redirector module a powershell check for the aliveness of the iphlpsvc and if it is not activated then I turn it on (net start iphlpsvc / start-service iphlpsvc). Afterwards the module worked like a charm.

**Comment by enigma0x3** [comment]
Do you have the code? If so, feel free to submit a pull. If not, I will get around to looking into this shortly. 

Thanks

**Comment by spivi** [comment]
No need.
I will gladly submit a pull during the day.
Thank you,
Great project !
