### ISSUE TITLE
Credentials truncated in Creds DB

### ISSUE THREAD

**Issue by jamcut** [PowerShellEmpire/Empire#27]
Hey guys,

First of all, thank you for this tool.  I have been using it pretty frequently since its release and I've been finding it quite useful.  However, I did notice something funky with the credential reporting.  When running the "mimikatz" command from an agent context, all the credentials are reported correctly, as expected.

![image](https://cloud.githubusercontent.com/assets/3229709/9442149/3ea26748-4a48-11e5-8bd8-b9a9de6d5ddf.png)

However, when running the "creds" command the same password in the above image is reported incorrectly.  I didn't dive into the code to see whats really happening, but I thought maybe it was truncating the output due to the ":" in the password. 

![image](https://cloud.githubusercontent.com/assets/3229709/9442229/ceeedfc0-4a48-11e5-894d-de8d6881aa2c.png)

Unfortunately, I can't provide too much information as this is from a client engagement, however if you need any assistance recreating the issue, I'll provide whatever help I can.

**Comment by enigma0x3** [comment]
Hey @jamcut, 
The code parses the mimikatz output with the ":", meaning any credentials with ":" inside them will get truncated. We will work on getting this fixed. 

Thanks!

**Comment by jamcut** [comment]
Awesome, thanks for the quick response!

**Comment by sixdub** [comment]
hey @jamcut , We found the bug and have it fixed in a branch. Once the branch gets tested, we will merge with master. Should be about a day... Thanks for finding this bug for us!!!
