### ISSUE TITLE
The restfull api don't start the listeners

### ISSUE THREAD

**Issue by tristandostaler** [PowerShellEmpire/Empire#272]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Ubuntu server, python 2.7.6

When we start the server normally, we can create new agents and interact with them. 
When we start the server with ./empire --rest --password="somepassword", the listeners are not started (or so I think) and we then can't interact with or create new agents.

**Comment by tristandostaler** [comment]
If you start the server with ./empire --password="somepassword" --headless instead, everything works well!

**Comment by tristandostaler** [comment]
Just found this in the code:

 if startEmpire:
        # if we want to start a full-running empire instance
        print " * Starting a full Empire instance"
        main = empire.MainMenu(args=args)
    else:
        # if we just want the RESTful API, i.e. no listener/etc. startup
        main = empire.MainMenu(args=args, restAPI=True)


---> # if we just want the RESTful API, i.e. no listener/etc. startup

Aka, in --rest, there is no litener by design. I am not sure I understand the logic?

If it is normal, you can close the issue.

**Comment by HarmJ0y** [comment]
Yes, this is the intended functionality - if you already have an Empire server running, you can start a RESTful API instance for it separately. Headless gives you a complete operating server.
