### ISSUE TITLE
Feature request: screenshot module tweaks

### ISSUE THREAD

**Issue by Viss** [PowerShellEmpire/Empire#273]
Some things that would be really really handy for the screenshot module
- the ability to define where the captured screenshots are placed. To specify an output dir for all screenshots so they all end up in one place.
- the name of the workstation (netbios name?) in the image filename
- the ability to run the screenshot module on a timer (every 5 min etc)

I'm doing this all by hand right now, but this would help tremendously in circumstances where you are "looking for someone" in the org, and you have shelled every machine and you end up screenshotting several hundred desktops to find them.

**Comment by HarmJ0y** [comment]
We've looked into the timer model for screenshots, but it got put on hold for some reason. We likely won't integrate the output directory suggestion but will look into possibly including the netbios name in the file output.

**Comment by HarmJ0y** [comment]
Commit https://github.com/PowerShellEmpire/Empire/commit/7167f225004965d055c1a613f64c778d14f7b434 to dev should add hostnames to the screenshot files.
