### ISSUE TITLE
meterpreter session invalid

### ISSUE THREAD

**Issue by dazzahome** [PowerShellEmpire/Empire#276]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Kali Linux 2.0 latest updates
Framework: 4.12.9-dev
Console  : 4.12.9-dev
The victim is a windows 7 box. Tried both X64 and x86 listeners.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

when using a meter payload in any stager (bat, macro etc) it connects back but responds after a couple of seconds . 

[-] Meterpreter session 1 is not valid and will be closed
[*] 10.0.0.134 - Meterpreter session 1 closed.

**Comment by HarmJ0y** [comment]
Empire stagers are only meant to be compatible with Empire. If this is a confirmed Empire issue, please feel free to open this back up with more information.
