### ISSUE TITLE
Hop functionality appears to not work

### ISSUE THREAD

**Issue by Viss** [PowerShellEmpire/Empire#279]
Either that or I'm unable to understand the documentation to make it go. Here's what I'm doing.

1) setup a listener, regular one, on port 8080. Call it 'listener1'
2) generate a hop.php, dump it to /var/www on that same server, running on port 80
3) create a hop listener, point it back at listener1 by setting the 'Host' parameter to the full url of the hop php: http://x.x.x.x:80/hop.php, and the 'RedirectTarget' to listener1
4) type 'launcher hop' into empire, get handed a payload to paste into cmdprompt
5) paste hop launcher powershell code into shell
6) tcpdump on attack host, observer this behavior:
    a) initial HTTP GET for /hop.php?<base64 string>
    b) additional comms back and forth between victim vm and attack host on port 80
    c) no shell pops
7) attempt to visit the /hop.php?<base64 string> by hand in browser, greeted with huge amount of base64.
8) copypaste off base64 blob to decode, find that it's a perl-golf style powershell function.
9) attempt to copypaste this function into a powershell file to run on it's on to see what happens
10) windows defender finds it (booo), so I turn off windows defender.
11) script execution policy complains, turn that off too
12) script is finally permitted to run, this is the output:

![image](https://cloud.githubusercontent.com/assets/1756255/16710489/350d4cfe-45e5-11e6-9d37-12c3c3775aeb.png)

13) attempt (poorly?) to identify and find place where missing squirly bracket is:

![image](https://cloud.githubusercontent.com/assets/1756255/16710512/3e350f00-45e6-11e6-99c3-6d51f6dd8042.png)

14) it appears to be at the end of the function line. Add squirly bracket there, attempt to run again
15) script appears to run and do nothing, tcpdump shows no attempted connections on port 80 or 8080
16) confused, turn to github to beg for help :D

**Comment by HarmJ0y** [comment]
We just pushed a small change to the dev branch at https://github.com/PowerShellEmpire/Empire/commit/7c5a07581d6fd7d40c7b41dca74324c8360868eb - let us know if this fixes or it's still an issue.

**Comment by Viss** [comment]
ohshitohshit!
I will go test it right now! \o/

**Comment by Viss** [comment]
Okay, I see the incoming request:

`[15/Jul/2016:18:39:37 -0400] "GET /hop.php?aHR0cHM6Ly80NS41NS40OC4xNzU6NDQzL2hvcC5waHAmaW5kZXguYXNw HTTP/1.1" 200 10084 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"`

It hits my apache logs. my windows vm just sorta makes a chime noise and no shell happens.
I should also mention that on this host I'm forcing things to https and using a letsencrypt cert. It LOOKS like that isn't a problem though - the initial request comes in and I can see it in the log, so its making it to hop.php, but after hop.php replies with whatever blob of code it does, nothing seems to happen.

I've tried it on the client box as well with exactly the same results.

**Comment by enigma0x3** [comment]
Hey @Viss,
Is this still an issue?

Thanks!

**Comment by Viss** [comment]
yup

**Comment by enigma0x3** [comment]
Cool,
I will look at it this week. Hacker summer camp kind of got in the way :P 

Thanks for the patience!

**Comment by Viss** [comment]
always!
let me know how I can be helpful!

**Comment by staaldraad** [comment]
My 2c (as I ran into this issue as well) - The fix from https://github.com/PowerShellEmpire/Empire/commit/7c5a07581d6fd7d40c7b41dca74324c8360868eb fixed the issue for me.

**Comment by horllste** [comment]
How does this hop_php work, opened it in browsers...nothing happened

**Comment by HarmJ0y** [comment]
The hop listener has been rewritten/simplified for the 2.0 branch, which will be released at DerbyCon in a few weeks. We'll revisit then.
