### ISSUE TITLE
Agent's "shell" command throws error

### ISSUE THREAD

**Issue by jaredbarez** [PowerShellEmpire/Empire#28]
![screenshot-area-2015-08-24-161409](https://cloud.githubusercontent.com/assets/13761356/9442342/bfe82f62-4a7b-11e5-976a-521fcfcb3c77.jpg)

**Comment by enigma0x3** [comment]
Is this a fresh pull? We made some changes to the internal agent functionality. Try doing a fresh git clone and then rerun the install script. Let me know the outcome of that.

**Comment by jaredbarez** [comment]
This wasn't a fresh pull but unfortunately I'll be offline for at least next 12 hrs to test... Will report.

**Comment by enigma0x3** [comment]
Thanks! Sorry for all the issues :)

**Comment by jaredbarez** [comment]
Not at all. I appreciate your efforts. By the way I just pulled  29c923ab261921b61a8bd7d4ca2facdd1ecb6fb8 and it works now!

**Comment by enigma0x3** [comment]
Sweet! Glad its working!
