### ISSUE TITLE
Questions Regarding Agent Output and Loops

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#282]
Hey there,

I'm working on a couple of simple modules and had a couple of questions.

1. Is it possible to have job output appear regardless of where you are in Empire?
2. Is it possible to have a job repeat n times (or until it's killed)?

Here are a couple of use cases:

- I'd like to monitor a user's computer until they launch a certain process or open a certain connection
- I'd like the notification of that alert to interrupt anything I'm doing so I can act on it

This was the result of a couple of finicky time-sensitive tasks I ran into on a recent engagement. Figured one or both would be helpful features in Empire.

**Comment by HarmJ0y** [comment]
Currently job output is resigned to Agent menus only to keep the main UI from being cluttered.

Jobs aren't currently repeatable, but we're thinking of trying to incorporate this into the architecture in a programatic way, just haven't had time to implement something "proper" yet. But we will revisit :)
