### ISSUE TITLE
Feature Request: Job Description

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#283]
It'd be super helpful if the output of the jobs command showed which module the job was associated with. Easier than scrolling back through the logs to figure out which was which.

**Comment by HarmJ0y** [comment]
We don't do this as a basic "opsec" type thing as the jobs architecture is built on PowerShell jobs and those names can be retrieved. Once we revamp the jobs architecture post BlackHat we will revisit.
