### ISSUE TITLE
Creds Export Doesn't Escape Commas

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#285]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Linux kali 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux
Python 2.7.11+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Kind of a silly bug, but it's there and I saw it, so here we are. When exporting the credentials database to CSV, commas in the password field cause additional columns to be created in the resulting CSV. Suspect this can be escaped but haven't dug into it yet.

**Comment by HarmJ0y** [comment]
This should be fixed in the dev branch with https://github.com/PowerShellEmpire/Empire/commit/fe43560bad3f35c453dab6a9815d0757bc279ebb - all fields are now "" wrapped to prevent text commas from mucking up the csv format.
