### ISSUE TITLE
Feature request - RAM disk

### ISSUE THREAD

**Issue by tristandostaler** [PowerShellEmpire/Empire#287]
I read two links about this thing:

https://www.tekrevue.com/tip/create-10-gbs-ram-disk-windows/
http://www.laptopmag.com/articles/faster-than-an-ssd-how-to-turn-extra-memory-into-a-ram-disk

So this is a feature request: having the possibility to create a Disk in RAM so almost every module not OpSec safe now could be.

I plan on doing it but I don't have the time right now so I put it here if someone have the time :)

**Comment by tristandostaler** [comment]
Might be worth looking into:

http://www.eterlogic.com/help/vdsdk/CSharpPage.html

**Comment by void-in** [comment]
@tristandostaler I am not sure it would be useful for opsec. The opsec unsafe modules are not unsafe because they usually read data from the disk storage (e.g. read Firefox SQLite db for credentials which is stored on the disk) and because of that interaction with the disk, a lot of data remnants can left behind. That problem can't be solved with a RAM disk.

**Comment by HarmJ0y** [comment]
Interesting idea. FYI the OpsecSafe flag isn't just concerned with touching disk, it's also set for anything that displays something to the user.

However I'm failing to really see what this gains us. If a part of RAM is exposed and mounted as a disk drive, AV solutions would still be able to scan/scrub. A RAM disk also wouldn't be applicable to persistence.

I'm going to close this for now but we'll consider looking into it if there's a reasonable case to be made for its use.

**Comment by tristandostaler** [comment]
Sure. Thanks!
Thanks also for the info about OpsecSafe!

I did not read enough on the subject but I have a few idea. I will test to see if it's something worth adding and if so, come back to you.
