### ISSUE TITLE
the "-enc" string in powershell commands is being flagged by a/v as bad.

### ISSUE THREAD

**Issue by Viss** [PowerShellEmpire/Empire#288]
This may explain why "some stuff doesn't work", as it's likely a/v is killing the command behind the scenes.

Recommend changing it to "-EncodedCommand", that seems to fix it.

**Comment by HarmJ0y** [comment]
At this point, we don't want to get into a race with every AV engine that's out there. If you want to change the launching parameters yourself, you can do so in [helpers.py](https://github.com/PowerShellEmpire/Empire/blob/c2ba61ca8d2031dad0cfc1d5770ba723e8b710db/lib/common/helpers.py#L165).
