### ISSUE TITLE
Agents wont kill

### ISSUE THREAD

**Issue by n00shE** [PowerShellEmpire/Empire#290]
## Empire Version
Newest

## OS Information (Linux flavor, Python version)
Kali Nethunter 3.1, 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Attempt to kill agents both using kill all and individually. Still appear to be up.

**Comment by leesoh** [comment]
Hey @n00shE, are you sure they're still online? If the server can't communicate with the agent, they just kinda hang around and you need to use ```remove``` rather than ```kill```

**Comment by n00shE** [comment]
thank you I feel like an idiot @leesoh
