### ISSUE TITLE
Feature request - Small modification in the readme

### ISSUE THREAD

**Issue by tristandostaler** [PowerShellEmpire/Empire#291]
We created a GUI in java (cross platform) for PowerShell Empire:
https://github.com/tristandostaler/EmpireGUI

So I wanted to let you know.
Also, maybe we can add the link also in the readme?

I also will accept pull request!
The project is not over, it still needs a few features!

**Comment by enigma0x3** [comment]
Hey @tristandostaler,
Cool GUI! We will consider adding it to the documentation after we have time to test it, etc. I'm going to close this for now but put it in the hopper to check out.

Thanks! :)

**Comment by tristandostaler** [comment]
Cool!
Keep in mind that the project is not over and it needs some more work done :)

Thanks!
