### ISSUE TITLE
Feature request - web backdoor - web relay

### ISSUE THREAD

**Issue by tristandostaler** [PowerShellEmpire/Empire#292]
I plan on doing it but I put it here if someone has the time to do it before me.

I tought that it would be interesting to have a web backdoor (say in php and/or asp) that run on a host with an agent and relay every calls it receives on the backdoor to the agents. So it would be a pivot using a php (or else) script in the "legit" web site. 

Example:
I have pwned a windows server and I have an agent on it and it runs a web server. If I want to pivot the classical way, I need to open a port in some way. If it is not possible, the pivot won't work. But if I have a script listening on port 80 (or 443) from the real web site, I could bypass this limitation. The script would just relay the call to the agents and then to the server.
And we could also have a script relaying to a script relaying to an agent (etc.).
It also offer the possibility to have only one agent make noise to the C&C and all the rest points to the first server. So from all the calls made, only 1 computer make calls to an IP unknown.

I don't know if my idea is clear? :P

**Comment by HarmJ0y** [comment]
Yes it is clear- we actually already [have this implemented](http://www.powershellempire.com/?page_id=102). Set the listener type to **hop**, set the redirect target and execute it, then **usestager hop_php <LISTENER_NAME>** to generate the hop.php file.

**Comment by tristandostaler** [comment]
Oh wow ok really nice! Thanks!
