### ISSUE TITLE
Download and execute feature request.

### ISSUE THREAD

**Issue by horllste** [PowerShellEmpire/Empire#294]
thia is not an issue, its a feature request, i dont know if it already exist in a module but i cant find it.

am thinking about a download and execute command/module to download and run anything on a connected agent.

thanks for the good work.

**Comment by enigma0x3** [comment]
Are you referring to a module that automatically uploads something (like an exe) and then execute it?

**Comment by horllste** [comment]
yes please, or it does it exist already?

thanks

**Comment by leesoh** [comment]
@horllste What were you looking to run? There is an ```upload``` functionality built into the agent along with the ability to run it using ```shell evil.exe```

**Comment by HarmJ0y** [comment]
This doesn't really make sense as an additional module as the functionality exists in the project already through upload/normal PowerShell command execution, so closing this issue.
