### ISSUE TITLE
Feature Request: Autoexecute on connect

### ISSUE THREAD

**Issue by itpropro** [PowerShellEmpire/Empire#299]
It would be great to define one or more modules, that autoexecute on agent connect. I think it would make sense, to configure it on a listener base. With this you would be able to automatic enroll persistence for example. As an alternative there could be a few more parameters on the listener like "Persistence" set to True and "Persistence Method" set to Registry, WMI etc..
It would be great if you would consider such a feature.

**Comment by enigma0x3** [comment]
You can do this on a per-module basis: https://github.com/PowerShellEmpire/Empire/issues/80

**Comment by itpropro** [comment]
I looked everywhere in the source except where it was implemented... Thanks for the fast reply and keep up the great work!
