### ISSUE TITLE
Api, undefined variable

### ISSUE THREAD

**Issue by insta** [PowerShellEmpire/Empire#300]
## Empire Version

1.5
## OS Information (Linux flavor, Python version)
4.6.0-kali1-amd64
Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When using the api to execute a module that has an "OutputExtension" set, an error due to incorrectly named variables is reached ( lines 439 and 451 ), the variable should be named module_name.

## Screenshot of error, embedded text output, or Pastebin link to the error
NameError("global name \'moduleName\' is not defined",)

**Comment by HarmJ0y** [comment]
This should be fixed on the dev branch with https://github.com/PowerShellEmpire/Empire/commit/fa2700b9b982a6a7582a851a7dd2b23c27913045
