### ISSUE TITLE
Windows Defender catches mimikatz and bypassuac

### ISSUE THREAD

**Issue by Raikia** [PowerShellEmpire/Empire#306]
## Empire Version
1.5.0 (commit e07e7ca)

## OS Information (Linux flavor, Python version)
Ubuntu 16.04
Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Windows Defender for Windows 10 now catches powershell execution of both bypassuacs and mimikatz.

## Screenshot of error, embedded text output, or Pastebin link to the error
![Error](http://i.imgur.com/d4obnrY.png)

**Comment by Raikia** [comment]
I can confirm it also pops up a window to the user notifying the user of malicious activity!  Its only the absolute latest version of windows defender

**Comment by HarmJ0y** [comment]
We don't want to get into a cat-mouse game with antivirus. You can edit any of the module sources at https://github.com/PowerShellEmpire/Empire/tree/master/data/module_source if you'd like in order to try to bypass certain solutions.
