### ISSUE TITLE
collection/keylogger catches keystrokes out of order, displays to user in semi-broken, partially unreadable manner

### ISSUE THREAD

**Issue by Viss** [PowerShellEmpire/Empire#308]
## Empire Version
Newest master branch (8/22/16)

here's a really horrible example, and yes, I'm a child  :)

![image](https://cloud.githubusercontent.com/assets/1756255/17901948/22275db6-691a-11e6-95d7-a9d25d1fbad0.png)

You can see that when the user hits 'backspace', in the log, it actually also hits backspace in addition to typing out [Backspace], so if someone were to say, type..

passwrd<backspace><backspace>ord

the logger would produce passw[Backspace[Backspaceord, and when these circumstances happen quickly, they overlap eachother which makes the log harder and harder to read - especially if it's a password you're after and its not easily visible that its typoed, or backwards, or the characters came in in the wrong order.

You can also see that the first instance of the word 'password', the logger captured an extra 'o' character.

**Comment by leesoh** [comment]
Potentially related to #49

**Comment by HarmJ0y** [comment]
Yep, duplicate. The async interval is as low as can go at this point. There's new KeyLogging code in PowerSploit but it only logs out to a file, so it hasn't been integrated. If we are able to adapt that dev code to output to the console, we will integrate it in Empire.
