### ISSUE TITLE
List taskings / autoruns

### ISSUE THREAD

**Issue by Viss** [PowerShellEmpire/Empire#309]
It would be really neat to be able to see what modules have been set to autorun once having set them to validate that their settings are correct. At the moment I can't find a way to display what autoruns have been setup/enabled. 

I can "clear them all", but at the moment I basically have to memorize what's set to autorun since I can't find a way to display that. 

Does that exist already or is there not actually a way to list taskings or autoruns?

**Comment by enigma0x3** [comment]
Currently, you can only have 1 module set to auto-run. There is some chatter about expanding auto-run features here: https://github.com/PowerShellEmpire/Empire/issues/311, so I'm going to go ahead and close this one out.
