### ISSUE TITLE
Path to database invalid

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#36]
When running the "setup_database.py" according to the website http://www.powershellempire.com/?page_id=110 the path to the empire.db is incorrect.
```
~/empire# python setup/setup_database.py

 [>] Enter server negotiation password, enter for random generation:
Traceback (most recent call last):
  File "setup/setup_database.py", line 76, in <module>
    conn = sqlite3.connect('../data/empire.db')
sqlite3.OperationalError: unable to open database file
root@python:~/empire#

```

**Comment by enigma0x3** [comment]
Running setup_database.py was never intended to be ran independently..it is just used by the install and reset scripts. You can edit the config either inside Empire or through the sqlitebrowser in kali. You can read more about it at the bottom of this article:
https://enigma0x3.wordpress.com/2015/08/26/empire-tips-and-tricks/
