### ISSUE TITLE
Cert.sh not in 'data'

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#37]
According to the site the cert.sh should be under data: `The provided ./data/cert.sh script will generate a self-signed cert and place it in ./data/empire.pem.` - it's under the setup directory

**Comment by mubix** [comment]
This should probably be automatically generated as part of the setup process, with some default information then give documentation on how to build one yourself

**Comment by enigma0x3** [comment]
I updated the website with the correct path. We will look into the option of automatically generating one with the setup process.
