### ISSUE TITLE
Feature Request - Add creds manually

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#39]
I can't see a way to add credentials manually (if retrieved through other means) 

Will look at the database to see if I can add manually through there in the mean time

**Comment by enigma0x3** [comment]
Hey @mubix,
You can add credentials manually by typing "creds add <domain> <username> <password>"

**Comment by mubix** [comment]
sweet, would be nice to have a -h or something. Is there a cred delete?

**Comment by enigma0x3** [comment]
something like this exists. if you type creds add (if you double tab after "creds", you will see your options). typing creds add -h (or something random), you will get the format needed. same for creds remove. This post covers some of these smaller things: https://enigma0x3.wordpress.com/2015/08/26/empire-tips-and-tricks/
