### ISSUE TITLE
mimikatz certs module exports to where?

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#41]
It exports the certs, but not sure if it goes to a local directory or where. I can't find them on my attack box and there isn't a way to interface with the file system easily from the agents menu that I can tell in order to find the files on target.

**Comment by mubix** [comment]
I did find that I could issue `ps` and `ls` command from the agents menu, but those command aren't listed as available. is there a sub menu some where where I can find out what options I have to run when interacting with an agent?

**Comment by enigma0x3** [comment]
Let me look into the cert thing. 

As far as commands go, you can type "help" in the agent menu to get a listing. You can also type "help agentcmds" to get a list of commands

**Comment by enigma0x3** [comment]
For the certs, it exports them to C:\Users\[user]\Documents

**Comment by mubix** [comment]
@enigma0x3 would be nice if the module automatically pulled them down and deleted them from the disk
