### ISSUE TITLE
Unique credentials

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#42]
I understand keeping around credentials that are the same but retrieved from two different source hosts (kinda), but if all other fields other that the ID and time field are the same it should probably just drop it from the listing so as not to clutter up the output

**Comment by pasv** [comment]
Time of retrieval is definitely worth while I would think... I've retrieved many a stale sessions that had differing passwords from what was actually in AD.

**Comment by enigma0x3** [comment]
We will add this to the release roadmap.

Thanks!
