### ISSUE TITLE
DCSync not working Part 2

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#45]
#40 for reference

After discussion with @gentilkiwi found out there is a /dc option for DCsync that works perfectly.

So:
Feature: add the /dc option for the DCSync module but leave it as not required
Bug: Figure out why the Job never finishes and just hangs in the job queue

**Comment by HarmJ0y** [comment]
Should be resolved with the most recent commit to master https://github.com/PowerShellEmpire/Empire/commit/fd1d17a647d21c11ffd3d5d0f53b11778744d0f1
