### ISSUE TITLE
Bind Loader ?

### ISSUE THREAD

**Issue by quentinhardy** [PowerShellEmpire/Empire#47]
Hello,

Very good project. Thank you :)

Is it possible to generate a Bind Powershell Loader (One-liner) with Empire? (and not a Reverse Loader)

In some case, a firewall can be between the target and the auditor with connection initializations from the target to the auditor's machine blocked.

I have not found this Bind feature in your project.

Thank you in advance,

**Comment by HarmJ0y** [comment]
Based on the async http[s] get/post methods that Empire uses, there's no way to build bind type communications into the architecture at this point. Even if we built a bind loader for the initial agent, communications could be over http[s] methods similar to the staging component.
