### ISSUE TITLE
Missing dependency in installer script

### ISSUE THREAD

**Issue by leechristensen** [PowerShellEmpire/Empire#5]
Empire requires the m2crypto python library, but the installer does not add it.  In addition, pip/easy_install both require swig (apt-get install swig) in order to build m2crypto dependencies

**Comment by enigma0x3** [comment]
Currently, we have only tested Empire installation on Kali. I believe that Kali (after apt-get update && apt-get ugprade) contains m2crypto already. What flavor are you running the script on?

**Comment by leechristensen** [comment]
That's what I figured.  Installed on a VPS running a fresh install of Ubuntu 14.04 LTS.

**Comment by enigma0x3** [comment]
Cool. I will spin up an Ubuntu 14.04 LTS box and test the installer script. We still need to work out a few kinks in adding support for more than just Kali :)

I'll leave this open and post back here once everything is updated and tested. Thanks for brining this up!

Matt

**Comment by enigma0x3** [comment]
Hey @leechristensen,
The installer script has been updated to include dependencies required for Ubuntu 14.04. Let us know if you encounter any issues.

Thanks!
