### ISSUE TITLE
Agent recognition

### ISSUE THREAD

**Issue by kostrahb** [PowerShellEmpire/Empire#56]
Hello, at first, let me thank you, this is very nice software to play with.
I had an idea that it might be quite easy to add some client recognition features, it's quite annoying that every time the powershell starts it creates new agent.
I think it should be possible write name to registry and then check that entry every time powershell (or other infected program) runs and send it to empire master.
Would it be possible?

**Comment by enigma0x3** [comment]
What do you mean by "everytime the powershell starts it creates a new agent"? To get a new agent, you would need to execute the launcher string or payload again. You should never get a new agent by just starting powershell.exe.

**Comment by kostrahb** [comment]
I am really sorry, I am learning how to use this software and I overlooked computer name column, as this is column should be used for orientation on which computer agent runs, this issue lost sense.
