### ISSUE TITLE
Powershell without Powershell

### ISSUE THREAD

**Issue by craigsmooth** [PowerShellEmpire/Empire#57]
This is more of a question. Just curious. In testing within an environment where powershell is blacklisted, I can get the agent deployed via reflective dll injection. However, I have had limited success with some of the modules. For example, screenshot works but keylogger does not (I get software restriction policy block event in eventlog for powershell.exe). Just curious what modules were "powershell without powershell" friendly. Is Empire a viable solution in a "powershell blacklisted" environment? Thanks!

**Comment by HarmJ0y** [comment]
At this point, any module with ["Background : True"](https://github.com/PowerShellEmpire/Empire/blob/master/lib/modules/collection/keylogger.py#L14]) set uses [PowerShell jobs](https://github.com/PowerShellEmpire/Empire/blob/master/data/agent/agent.ps1#L386) to kick the script off in the background. PowerShell jobs unfortunately do start a new powershell.exe process. If you're looking for a quick workground, you can set your modules to "Background : False", but if the module doesn't return (like the keylogger) then you won't be able to exit the agent.

We're looking into another approach for job backgrounding that doesn't rely on PowerShell jobs, but everything in an architectural tradeoff, and unfortunately a perfect solution does not exist yet. But we're trying to look into it :)
