### ISSUE TITLE
Tab complete bug in "usestager"

### ISSUE THREAD

**Issue by leechristensen** [PowerShellEmpire/Empire#6]
Type in "usestager h<tab><tab>" or "usestager l<tab><tab>".  It's wanting to tab-complete the word "listener" instead of the various stagers

**Comment by enigma0x3** [comment]
What menu context are you doing this from? i.e (main empire menu, agents menu, etc)

**Comment by leechristensen** [comment]
So far it's anywhere that the "usestager" command is available.  I've tested the main menu, agents, and listeners menus.

FWIW, running here's some environmental info:
Ubuntu 14.04
Python version(per sys.version): '2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]'
Running inside of a screen session

**Comment by leechristensen** [comment]
Sorry, I just realized Github removed some text in the original report (used angle brackets instead of regular brackets in original report):

Type in "usestager h[TAB][TAB]"

**Comment by enigma0x3** [comment]
This has been fixed. If you do a pull, tab completion should work as expected.

Thanks!
