### ISSUE TITLE
 Error: invalid stager module

### ISSUE THREAD

**Issue by ravemandot** [PowerShellEmpire/Empire#60]

**Comment by enigma0x3** [comment]
@ravemandot,
Please provide information about this.

Thanks.

**Comment by enigma0x3** [comment]
@ravemandot,
Looking through the source, I was able to pick apart what you are seeing. When typing "usestager", you have to supply what stager you want to use. Syntax will be "usestager <stagerName> <listener>". You can view all the available stagers by typing "usestager" and then pressing tab twice.

Thanks

**Comment by ravemandot** [comment]
Thank You!!! enigma0x3. Sorry for my lack of attention.
