### ISSUE TITLE
Feature Request: Interface to modify the stage URLs

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#62]
Currently there isn't a very simple way to change the stager URLs. It would be nice to have the ability in the UI to change these and hopefully even to so per-listener.

**Comment by enigma0x3** [comment]
Hey @mubix,
We currently have a list of features that will eventually be integrated into future releases. I have placed this on the list and we will take a look at the underlying architecture to make sure this feature fits well within the framework.

Thanks for the suggestion, we will dev this and test it out! Hopefully it will appear in a future release.
