### ISSUE TITLE
Module error running Empire

### ISSUE THREAD

**Issue by dark668** [PowerShellEmpire/Empire#65]
Hi on initial install Empire was working fine, not sure what has changed or if its a kali/python issue:
checked that I've got the latest pull from git also tried googling with no luck a point in the right direction would be greatly appreciated: 

root@kali:/opt/Empire# ls
changelog  data  empire  lib  LICENSE  README.md  setup
root@kali:/opt/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 6, in <module>
    from lib.common import empire
  File "/opt/Empire/lib/common/empire.py", line 15, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch
root@kali:/opt/Empire# python -V
Python 2.7.3
root@kali:/opt/Empire# pip install pydispatch
Requirement already satisfied (use --upgrade to upgrade): pydispatch in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.7 in /usr/local/lib/python2.7/dist-packages (from pydispatch)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pydispatch)
Cleaning up...
root@kali:/opt/Empire# pip install pydispatch --upgrade
Requirement already up-to-date: pydispatch in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: colorama>=0.2.7 in /usr/local/lib/python2.7/dist-packages (from pydispatch)
Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pydispatch)
Cleaning up...
root@kali:/opt/Empire#

**Comment by enigma0x3** [comment]
Sounds like a kali/python issue. Can you go into the setup folder and run ./install and ./reset and see what happens?

**Comment by dark668** [comment]
root@kali:/opt/Empire/setup# ./install.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version.
The following packages were automatically installed and are no longer required:
  libhttp-parser2.1 ruby-ansi ruby-dataobjects ruby-dataobjects-mysql ruby-dataobjects-postgres ruby-dataobjects-sqlite3 ruby-dm-core ruby-dm-do-adapter
  ruby-dm-migrations ruby-dm-sqlite-adapter ruby-em-websocket ruby-execjs ruby-http-parser.rb ruby-librex ruby-libv8 ruby-msfrpc-client ruby-parseconfig ruby-ref
  ruby-therubyracer
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  libhttp-parser2.1 ruby-ansi ruby-dataobjects ruby-dataobjects-mysql ruby-dataobjects-postgres ruby-dataobjects-sqlite3 ruby-dm-core ruby-dm-do-adapter
  ruby-dm-migrations ruby-dm-sqlite-adapter ruby-em-websocket ruby-execjs ruby-http-parser.rb ruby-librex ruby-libv8 ruby-msfrpc-client ruby-parseconfig ruby-ref
  ruby-therubyracer
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-m2crypto is already the newest version.
The following packages were automatically installed and are no longer required:
  libhttp-parser2.1 ruby-ansi ruby-dataobjects ruby-dataobjects-mysql ruby-dataobjects-postgres ruby-dataobjects-sqlite3 ruby-dm-core ruby-dm-do-adapter
  ruby-dm-migrations ruby-dm-sqlite-adapter ruby-em-websocket ruby-execjs ruby-http-parser.rb ruby-librex ruby-libv8 ruby-msfrpc-client ruby-parseconfig ruby-ref
  ruby-therubyracer
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
swig is already the newest version.
The following packages were automatically installed and are no longer required:
  libhttp-parser2.1 ruby-ansi ruby-dataobjects ruby-dataobjects-mysql ruby-dataobjects-postgres ruby-dataobjects-sqlite3 ruby-dm-core ruby-dm-do-adapter
  ruby-dm-migrations ruby-dm-sqlite-adapter ruby-em-websocket ruby-execjs ruby-http-parser.rb ruby-librex ruby-libv8 ruby-msfrpc-client ruby-parseconfig ruby-ref
  ruby-therubyracer
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): iptools in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): pydispatcher in /usr/local/lib/python2.7/dist-packages
Cleaning up...

 [>] Enter server negotiation password, enter for random generation: test
Traceback (most recent call last):
  File "./setup_database.py", line 98, in <module>
    )''')
sqlite3.OperationalError: table config already exists
root@kali:/opt/Empire/setup# ls
cert.sh  install.sh  reset.sh  setup_database.py
root@kali:/opt/Empire/setup# ./reset.sh

 [>] Enter server negotiation password, enter for random generation: test

 [*] Database setup completed!

rm: cannot remove `empire.debug': No such file or directory
Traceback (most recent call last):
  File "./empire", line 6, in <module>
    from lib.common import empire
  File "/opt/Empire/lib/common/empire.py", line 15, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch
root@kali:/opt/Empire/setup#

**Comment by enigma0x3** [comment]
What version of Kali is this on?

**Comment by dark668** [comment]
Kali 1.0.8

root@kali:/opt/Empire/setup# uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

**Comment by enigma0x3** [comment]
Could be something with the python packages. Is this a fresh install? If so, I will find a 1.0.8 image and test it.

**Comment by dark668** [comment]
Nope it one I've had for a while, ill look into trouble shooting the python and post back if I fix it, ta for the assist.

**Comment by enigma0x3** [comment]
Cool. Let me know what you find and let me know if there is anything I can do.
