### ISSUE TITLE
Psinject wont work on win7

### ISSUE THREAD

**Issue by kokoown** [PowerShellEmpire/Empire#67]
It works perfectly on win8 but on win7 it's not even start the dll...
Any help?

**Comment by enigma0x3** [comment]
What process are you trying to inject into to and how are you running the command?

**Comment by enigma0x3** [comment]
I'm able to confirm that this does work on Windows 7 and am unable to reproduce. Please try injecting into a process like dwm by typing "psinject <listener> <procID>".

**Comment by kokoown** [comment]
I will try again. But i'm pretty sure it's not working...
How can i debug the script? Which var i should print for debug

**Comment by kokoown** [comment]
I have just started a new fresh empire install. And a new listener. And tried to inject to dwm. The powershell job was started and the window was opened on the victim. But then it got close. 
Its a freah windows 7 install
And everything is new

**Comment by enigma0x3** [comment]
What do you mean "the window was opened on the victim"?.

**Comment by kokoown** [comment]
A powershell window is opened and try to inject it to the process. I also tried to use reflective dll loader from powerpick project and its only load the dll in win8. In win it got error in importing the .net libraries. 
I tried to use other reflective dlls with the injector or with painject and it works! Only the dll from your project making problem in win 7

**Comment by kokoown** [comment]
I think its beacuse you are using .Net 4 with your dll. And win7 freah install has only .net 2. Maybe this is the problem?

**Comment by enigma0x3** [comment]
Please run this and paste the output here: gci "hklm:\SOFTWARE\Microsoft\NET Framework Setup\NDP"

**Comment by kokoown** [comment]
Victim Versions:
2.0.50727
3.0
3.5

**Comment by enigma0x3** [comment]
Ok, it might have something to do with the .NET version. It should support version 2-5, but I will test and verify.

**Comment by kokoown** [comment]
Ok thanks. 
I also tried to run the psinject code from powertools/powerpick and it's not working. Sharppick also worked only for .net 4 libraries. If you try to run it on .net 2 its reproting an error

**Comment by enigma0x3** [comment]
I removed version 4 and can verify that psinject does fail. We will take a look at this and get it fixed. Thank you for reporting this.

**Comment by leechristensen** [comment]
Nuts, looks like it's a bug in the UnmanagedPowerShell code.  I'll take a look at it as well

**Comment by leechristensen** [comment]
The culprit is my call to CLRCreateInstance to setup the runtime because it's only present in .NET 4+.  Should be using CorBindToRuntime instead to setup the runtime.  Here is some code that highlights the differences between the two loading methods:

https://github.com/EasyHook/EasyHook/blob/master/EasyHookDll/RemoteHook/entry.cpp

I should have some time tonight to fix it in case you don't get to it by then.

**Comment by enigma0x3** [comment]
Perfect, thanks!!

**Comment by kokoown** [comment]
Maybe you can download remotly the desiered .net 4 libaries in a ps .net 2. And then execute them within .Net2

**Comment by leechristensen** [comment]
@enigma0x3 I updated the UnmanagedPowershell (https://github.com/leechristensen/UnmanagedPowerShell).  It first tries to create the host using the .net 4.0 APIs.  If that fails, it will try the .net 2.0 APIs.  Worked on my Win7 test VM with .NET 2.0/3.5 installed, but additional testing is welcomed.

**Comment by leechristensen** [comment]
Also, I updated the the PowerShellRunner assembly in the UnmanagedPowerShell project a while back because some machines were complaining that the custom PSHost I created didn't have a name.  If that change didn't make it into PSInject/Empire, we might want to update that as well since we're making changes.

**Comment by enigma0x3** [comment]
You rock! We will get it updated! Thanks so much @leechristensen!!

**Comment by kokoown** [comment]
Why not to load just from .NET 2 and make the dll lighter?

**Comment by leechristensen** [comment]
Prior to .NET 4.0, different versions of the runtime could not be injected into the same process(e.g. .net 4.0 and .net 2.0 could not be loaded in the same process).  Using the 4.0 APIs, we can get around this.  I'll be honest, though, I haven't tested only using the .NET 2 APIs.

**Comment by kokoown** [comment]
Is it possible just to load the .Net no matter if its 2 or 4?
I think it's better method and keep everything lighter

**Comment by kokoown** [comment]
.net 2***

**Comment by kokoown** [comment]
leechristensen i check unmanaged powershell update and it's giving me error:
Msvcr120D.dll is missing

**Comment by leechristensen** [comment]
You can load just the .net runtime just using old 2.0 APIs, but you may run problems if you try to inject into a process that already has the .net runtime loaded.  By using the 4.0 APIs we can get around this.  Bear in mind that I have done no verification on this.  My understanding is based solely on what's in the docs and what other projects have done.

As for size, it only adds ~1K, which really isn't bad.  If you're concerned about size, then time would be better spent changing to an older compiler or minimizing the .net assembly.  

As for why it's not working, it needs to be in release mode.  You may need to static link the C runtime as well.

**Comment by kokoown** [comment]
״As for why it's not working, it needs to be in release mode. You may need to static link the C runtime as well.״
I didnt understand what should i do... Can you explaine a little more?

**Comment by wintermute4316** [comment]
Trying out Empire for the first time this week.  Testing against Windows 7 Enterprise 64-bit and I noticed a similar issue with psinject.  The initial powershell agent works fine and I'm in a powershell process as a domain user that's member of the local Administrators groups on this system. powerup/allchecks confirms this showing "Current user already has local administrative privileges".  Running bypassuac reports "Not in a medium integrity process" and bypassuac_wscript reports "You are already elevated", so it seems I already have the appropriate high integrity privileges.  However when I run ps and then try to psinject into a process with "nt authority/system" privileges, it starts the job, but I never get a call back with a new agent in that process.  Same result if I psinject into another process that my user owns.  I seem to have all the appropriate .NET pre-reqs in the reg entry that was listed higher in this thread: v2.0.x, v3.0, v3.5, v4, & v4.0.  Any ideas?

**Comment by wintermute4316** [comment]
Just to add some extra information, I added code to bypassuac (Invoke-BypassUAC) to provide an additional message in the console if "whoami /groups" has a "High Mandatory Level" group permission and indeed it does.  I believe this is also indicated by the asterisk prepending the username in the agents view, which it is as well. In that case, psinject (Invoke-PSInject) should have sufficient privileges to function, however when it executes against an agent, it starts the job, but nothing comes back. I've tried this with a few different test Win7 Enterprise 64-bit targets with same result.

**Comment by leechristensen** [comment]
@wintermute4316 that sounds like a somewhat different issue.  Are you calling out to an externally-hosted server? If so, you may want to verify that an NTLM proxy is not in use (SYSTEM processes won't be able to authenticate to the proxy).  Otherwise, you may want to open a separate issue.

@kokoown Those are Visual Studio configuration options.  I'll try and update the UnmanagePowerShell repo with them, but time is a bit sparse right now for me.  Otherwise, you may need to rely on Google to setup the options.

**Comment by wintermute4316** [comment]
Thanks for the response.  I'll open in a new issue.  Communications are between to internal (intranet) systems.  One Kali 1.1 latest hosting Empire and the other a Win7 Enterprise x64 host joined to a lab domain.  Domain credential that the agent is running under is a local Administrator on the Win7 host and agent is running with "High mandatory level" privileges.

**Comment by kokoown** [comment]
The unmanaged powershell works great on .net 2. I tried to load the .net 2 from the powershell runner (the dll) and it didnt work. Do you know when will be an update? Thanks for all the help

**Comment by enigma0x3** [comment]
I will get this tested as soon as I can. One of our developers modified the dlls a bit so I need to grab the code from him. Once it is updated, I will post back here. I apologize for the delay on this! Things have been a bit crazy :)

**Comment by enigma0x3** [comment]
Thanks for the quick update @leechristensen, it is always much appreciated =)

**Comment by enigma0x3** [comment]
@kokoown,
The dlls are now updated. Do a pull and give injection a try, should work now.

Thanks!

**Comment by kokoown** [comment]
Great its perfect!
Nice work!
There is a new issue - the injection always inject ps2 even if the computer has ps4
Should i pot a new bug?
