### ISSUE TITLE
New Psinject always inject ps2

### ISSUE THREAD

**Issue by kokoown** [PowerShellEmpire/Empire#71]
I dont want to annoy but i'm just writing it to let you know. For me its not a big deal. 
There is a new issue with the new psinject - the injection always inject ps2 even if the computer has ps4.

**Comment by enigma0x3** [comment]
hey @kokoown,
While this may occur, I can't think of why this would be an issue as injection will work regardless. Are you running into an issue as a result of injection using .NET 2 instead of 4?

**Comment by kokoown** [comment]
No. Not at all. Im just infore you

**Comment by enigma0x3** [comment]
Ahh, cool. Thanks! We will take a look at this. In the meantime, injection should work as expected.

Thanks for reporting it!
