### ISSUE TITLE
dll stager from last commit doesn't work in Cobalt Strike 3.0 Beacon

### ISSUE THREAD

**Issue by jaredbarez** [PowerShellEmpire/Empire#75]
![untitled](https://cloud.githubusercontent.com/assets/13761356/10819624/6d0f9d00-7e49-11e5-9fdc-c9580c284aff.png)

On the other side, this can be CS problem, not Empire's.

Commit e62c5866c0a664e62509dd9c241f6f0ae1abd00d

**Comment by enigma0x3** [comment]
We just updated the dlls to fix a bug in process injection, which might have broken this. I will take a look at it.

Thanks!

**Comment by pwnaus** [comment]
I can confirm this issue exists, replacing ReflectivePick_x64_orig.dll
and ReflectivePick_x86_orig.dll from commit c948fcd seemed to fix it.

Haven't had time to do any extensive testing yet tho....

**Comment by enigma0x3** [comment]
Just updated both dlls to fix this. Do a pull and it should work. Here is the commit: https://github.com/PowerShellEmpire/Empire/commit/123a2435a7d0db63d6f0fd4f03ebf1cf53c23626
