### ISSUE TITLE
Easy way to load external modules

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#81]
Much like Metasploit has their .msf4/modules directory, it would be nice if there was a way for custom modules to be loaded outside of Empire so I don't have to dirty up my Empire directory with all my janky powershell code ;-)

**Comment by enigma0x3** [comment]
Hey @mubix,
You can keep your stuff separated by simply creating a new folder in empire/lib/modules and putting your modules there. it will load up for you and allow you to keep your code separated from the frameworks current modules.

**Comment by HarmJ0y** [comment]
We revisited this and implemented it with commit https://github.com/PowerShellEmpire/Empire/commit/c6662d8a3a2a63f43b67d9ab0e6c87e6aea017c2 . 

On the main menu, 'load /dir/path/to/modules' will load an external module directory, accessible by 'usemodule external/nested/path/module'.
