### ISSUE TITLE
Feature request: get SID for forest root from within Empire?

### ISSUE THREAD

**Issue by wintermute4316** [PowerShellEmpire/Empire#86]
In this great blog post: http://www.harmj0y.net/blog/redteaming/mimikatz-and-dcsync-and-extrasids-oh-my/ is the following quote:

----
Then we need the SID of the forest root. I’m sure there are better ways to do this, but one easy one is to resolve the ‘krbtgt’ account for the domain:
(New-Object System.Security.Principal.NTAccount("testlab.local","krbtgt")).Translate([System.Security.Principal.SecurityIdentifier]).Value
----

This method for getting the forest root SID from a child domain requires running the above one-liner powershell command.  Is there a way to run this one-liner from inside Empire against one of the agents?  Or another option, can this one-liner be incorporated into the existing module situational_awareness/network/powerview/get_forest_domain?

**Comment by HarmJ0y** [comment]
This should now be live on master in the [**situational_awareness/network/powerview/get_forest**](https://github.com/PowerShellEmpire/Empire/blob/master/lib/modules/situational_awareness/network/powerview/get_forest.py) module. The SID of the root domain is added into the resulting Forest object.

<img width="815" alt="root_domain_sid" src="https://cloud.githubusercontent.com/assets/5504523/11023792/6b11af48-8650-11e5-83e5-fecb5c96364e.png">

This has also been added to PowerView as well https://github.com/PowerShellEmpire/PowerTools/commit/79c7db418912771bd0f20fc8351024517442f41f

Thanks for the suggestion!
